// Copyright 2026 James Casey
// SPDX-License-Identifier: Apache-2.0

//! Native facade code generation for `native:` actor classes (ADR 0056).
//!
//! **DDD Context:** Compilation — Code Generation
//!
//! For `native:` classes, generates a thin facade module instead of a full
//! `gen_server` module. The facade delegates spawn to `BackingModule:start_link/1`
//! and provides `has_method/1`, `__beamtalk_meta/0`, and `register_class/0`.
//!
//! Dispatch functions for `self delegate` methods are generated by BT-1210.

use super::super::document::{Document, INDENT, line, nest};
use super::super::spec_codegen;
use super::super::{CodeGenContext, CoreErlangGenerator, Result};
use crate::ast::{MethodKind, Module};
use crate::docvec;
use crate::unparse::unparse_method_display_signature;

impl CoreErlangGenerator {
    /// Generates a native facade module for a `native:` actor class (ADR 0056).
    ///
    /// Instead of a full `gen_server` module with `init`/`handle_cast`/`handle_call`/etc.,
    /// this generates a lightweight facade that:
    /// - `spawn/1` calls `BackingModule:start_link(Config)` and wraps as `#beamtalk_object{}`
    /// - `spawn/0` calls `spawn/1` with an empty map
    /// - `has_method/1` returns true for all declared selectors
    /// - `__beamtalk_meta/0` includes `native => true` and `backing_module => atom()`
    /// - `register_class/0` registers via `ClassBuilder` with `native:` metadata
    ///
    /// Dispatch functions for `self delegate` methods are out of scope (BT-1210).
    #[allow(clippy::too_many_lines)]
    pub(in crate::codegen::core_erlang) fn generate_native_facade_module(
        &mut self,
        module: &Module,
    ) -> Result<Document<'static>> {
        self.context = CodeGenContext::Actor;
        self.setup_class_identity(module);

        let has_classes = !module.classes.is_empty();

        // BT-411: Build class method exports
        let class_method_export_doc = Self::build_class_method_export_doc(module);

        // BT-586: Generate spec attributes from type annotations
        let spec_attrs = module
            .classes
            .first()
            .map(|class| spec_codegen::generate_class_specs(class, false))
            .unwrap_or_default();
        let spec_suffix: Document<'static> = spec_codegen::format_spec_attributes(&spec_attrs)
            .map_or(Document::Nil, |s| docvec![",\n     ", s]);

        // BT-745: Build beamtalk_class attribute
        let beamtalk_class_attr = super::super::util::beamtalk_class_attribute(&module.classes);

        // BT-845/BT-860: Source path attribute
        let source_path_attr = self.source_path_attr();
        // BT-940: File attribute for stacktraces
        let file_attr = self.file_attr();

        // Native facade exports: spawn, new errors, reflection, class methods, registration
        let base_exports: Document<'static> = docvec![
            "'spawn'/0, 'spawn'/1, 'new'/0, 'new'/1, \
             'has_method'/1, 'method_table'/0, 'class_name'/0, 'superclass'/0",
            if has_classes {
                Document::Str(", '__beamtalk_meta'/0")
            } else {
                Document::Nil
            },
        ];

        let mut docs: Vec<Document<'static>> = Vec::new();

        // Module header
        let module_header = if has_classes {
            docvec![
                "module '",
                Document::String(self.module_name.clone()),
                "' [",
                base_exports,
                class_method_export_doc,
                ", 'register_class'/0]",
                "\n",
                "  attributes ['on_load' = [{'register_class', 0}]",
                beamtalk_class_attr,
                file_attr,
                source_path_attr,
                spec_suffix,
                "]\n",
            ]
        } else {
            docvec![
                "module '",
                Document::String(self.module_name.clone()),
                "' [",
                base_exports,
                class_method_export_doc,
                "]",
                "\n",
                "  attributes [",
                file_attr,
                source_path_attr,
                spec_suffix,
                "]\n",
            ]
        };
        docs.push(module_header);
        docs.push(Document::Str("\n"));

        // Helper: push a generated function + newline separator
        let mut push_fn = |doc: Document<'static>| {
            docs.push(doc);
            docs.push(Document::Str("\n"));
        };

        // spawn/0 and spawn/1 — delegate to BackingModule:start_link/1
        let backing_module = module
            .classes
            .first()
            .and_then(|c| c.backing_module.as_deref())
            .expect("native facade requires backing_module");

        push_fn(self.generate_native_spawn_0()?);
        push_fn(self.generate_native_spawn_1(backing_module)?);

        // new/0 and new/1 error methods (actors can't use new)
        push_fn(self.generate_actor_new_error_method()?);
        push_fn(self.generate_actor_new_with_args_error_method()?);

        // superclass/0 and class_name/0
        push_fn(self.generate_superclass_function(module)?);
        push_fn(self.generate_class_name_function(module)?);

        // method_table/0
        push_fn(self.generate_method_table(module)?);

        // has_method/1
        docs.push(self.generate_has_method(module)?);

        // BT-411: Generate class-side method standalone functions
        if let Some(class) = module.classes.first() {
            if !class.class_methods.is_empty() {
                docs.push(self.generate_class_method_functions(class)?);
            }
        }

        // __beamtalk_meta/0 and register_class/0
        if has_classes {
            docs.push(Document::Str("\n"));
            docs.push(self.generate_native_meta_function(module)?);
            docs.push(self.generate_native_register_class(module)?);
        }

        docs.push(Document::Str("end\n"));

        Ok(Document::Vec(docs))
    }

    /// Generates `spawn/0` for native facade — calls `spawn/1` with empty map.
    ///
    /// ```erlang
    /// 'spawn'/0 = fun () ->
    ///     call 'bt@stdlib@subprocess':'spawn'(~{}~)
    /// ```
    #[allow(clippy::unnecessary_wraps)]
    fn generate_native_spawn_0(&mut self) -> Result<Document<'static>> {
        let doc = docvec![
            "'spawn'/0 = fun () ->",
            nest(
                INDENT,
                docvec![
                    line(),
                    docvec![
                        "call '",
                        Document::String(self.module_name.clone()),
                        "':'spawn'(~{}~)",
                    ],
                ]
            ),
            "\n",
            "\n",
        ];
        Ok(doc)
    }

    /// Generates `spawn/1` for native facade — calls `BackingModule:start_link/1`.
    ///
    /// ```erlang
    /// 'spawn'/1 = fun (Config) ->
    ///     case call 'erlang':'is_map'(Config) of
    ///       <'false'> when 'true' ->
    ///         %% type_error for non-map arguments
    ///       <'true'> when 'true' ->
    ///         case call 'backing_module':'start_link'(Config) of
    ///           <{'ok', Pid}> when 'true' ->
    ///             {'beamtalk_object', 'ClassName', 'module_name', Pid}
    ///           <{'error', Reason}> when 'true' ->
    ///             %% instantiation_error
    ///         end
    ///     end
    /// ```
    #[allow(clippy::unnecessary_wraps)]
    #[expect(
        clippy::too_many_lines,
        reason = "native spawn-with-args handles map validation and error details"
    )]
    fn generate_native_spawn_1(&mut self, backing_module: &str) -> Result<Document<'static>> {
        let class_name = self.class_name();
        let module_name = self.module_name.clone();
        let hint_binary = Self::binary_string_literal("spawnWith: expects a Dictionary argument");

        let doc = docvec![
            "'spawn'/1 = fun (Config) ->",
            nest(
                INDENT,
                docvec![
                    line(),
                    "case call 'erlang':'is_map'(Config) of",
                    nest(
                        INDENT,
                        docvec![
                            line(),
                            "<'false'> when 'true' ->",
                            nest(
                                INDENT,
                                docvec![
                                    line(),
                                    docvec![
                                        "let TypeErr0 = call 'beamtalk_error':'new'('type_error', '",
                                        Document::String(class_name.clone()),
                                        "') in",
                                    ],
                                    line(),
                                    "let TypeErr1 = call 'beamtalk_error':'with_selector'(TypeErr0, 'spawnWith:') in",
                                    line(),
                                    docvec![
                                        "let TypeErr2 = call 'beamtalk_error':'with_hint'(TypeErr1, ",
                                        Document::String(hint_binary),
                                        ") in",
                                    ],
                                    line(),
                                    "call 'beamtalk_error':'raise'(TypeErr2)",
                                ]
                            ),
                            line(),
                            "<'true'> when 'true' ->",
                            nest(
                                INDENT,
                                docvec![
                                    line(),
                                    docvec![
                                        "case call '",
                                        Document::String(backing_module.to_string()),
                                        "':'start_link'(Config) of",
                                    ],
                                    nest(
                                        INDENT,
                                        docvec![
                                            line(),
                                            "<{'ok', Pid}> when 'true' ->",
                                            nest(
                                                INDENT,
                                                docvec![
                                                    line(),
                                                    // Instance registration for hot reload tracking
                                                    Self::instance_registration_doc(&class_name),
                                                    line(),
                                                    docvec![
                                                        "{'beamtalk_object', '",
                                                        Document::String(class_name.clone()),
                                                        "', '",
                                                        Document::String(module_name.clone()),
                                                        "', Pid}",
                                                    ],
                                                ]
                                            ),
                                            line(),
                                            "<{'error', Reason}> when 'true' ->",
                                            nest(
                                                INDENT,
                                                docvec![
                                                    line(),
                                                    docvec![
                                                        "let SpawnErr0 = call 'beamtalk_error':'new'('instantiation_error', '",
                                                        Document::String(class_name.clone()),
                                                        "') in",
                                                    ],
                                                    line(),
                                                    "let SpawnErr1 = call 'beamtalk_error':'with_selector'(SpawnErr0, 'spawnWith:') in",
                                                    line(),
                                                    "let SpawnErr2 = call 'beamtalk_error':'with_details'(SpawnErr1, ~{'reason' => Reason}~) in",
                                                    line(),
                                                    "call 'beamtalk_error':'raise'(SpawnErr2)",
                                                ]
                                            ),
                                        ]
                                    ),
                                    line(),
                                    "end",
                                ]
                            ),
                        ]
                    ),
                    line(),
                    "end",
                ]
            ),
            "\n",
            "\n",
        ];
        Ok(doc)
    }

    /// Generates `__beamtalk_meta/0` for native facade — includes `native` and `backing_module`.
    #[allow(clippy::unused_self)]
    #[allow(clippy::unnecessary_wraps)]
    fn generate_native_meta_function(&self, module: &Module) -> Result<Document<'static>> {
        let Some(class) = module.classes.first() else {
            return Ok(Document::Nil);
        };

        let backing_module = class
            .backing_module
            .as_deref()
            .expect("native facade requires backing_module");

        // Reuse the standard meta map and append native-specific keys
        Ok(docvec![
            "'__beamtalk_meta'/0 = fun () ->\n",
            "    ",
            Self::build_native_meta_map_doc(class, module, backing_module),
            "\n\n",
        ])
    }

    /// Builds the Core Erlang map for native facade `__beamtalk_meta/0`.
    ///
    /// Extends the standard meta map with:
    /// - `'native' => 'true'`
    /// - `'backing_module' => 'beamtalk_subprocess'`
    fn build_native_meta_map_doc(
        class: &crate::ast::ClassDefinition,
        module: &Module,
        backing_module: &str,
    ) -> Document<'static> {
        use crate::ast::ClassKind;

        let class_name = class.name.name.to_string();
        let superclass_name = class
            .superclass
            .as_ref()
            .map_or_else(|| "nil".to_string(), |s| s.name.to_string());

        // Build fields list — should be empty for native actors, but include for completeness
        let fields: Vec<String> = class
            .state
            .iter()
            .map(|s| s.name.name.to_string())
            .collect();
        let fields_doc = Self::meta_atom_list(&fields);

        // Boolean flags
        let is_sealed_doc = Self::meta_bool(class.is_sealed);
        let is_abstract_doc = Self::meta_bool(class.is_abstract);
        let is_value_doc = Self::meta_bool(class.class_kind == ClassKind::Value);
        let is_typed_doc = Self::meta_bool(class.is_typed);

        // field_types
        let field_types_doc = Self::meta_field_types_map(&class.state);

        // Method info (reuse standard helpers)
        let auto =
            crate::codegen::core_erlang::value_type_codegen::compute_auto_slot_methods(class);
        let method_info_doc = Self::meta_method_info_map(&Self::meta_instance_method_entries(
            class,
            module,
            auto.as_ref(),
            false,
        ));
        let class_method_info_doc = Self::meta_method_info_map(&Self::meta_class_method_entries(
            class,
            module,
            auto.as_ref(),
            false,
            false,
        ));

        docvec![
            "~{'class' => '",
            Document::String(class_name),
            "',\n      'superclass' => '",
            Document::String(superclass_name),
            "',\n      'fields' => ",
            fields_doc,
            ",\n      'is_sealed' => ",
            is_sealed_doc,
            ",\n      'is_abstract' => ",
            is_abstract_doc,
            ",\n      'is_value' => ",
            is_value_doc,
            ",\n      'is_typed' => ",
            is_typed_doc,
            ",\n      'field_types' => ",
            field_types_doc,
            ",\n      'method_info' => ",
            method_info_doc,
            ",\n      'class_method_info' => ",
            class_method_info_doc,
            ",\n      'native' => 'true'",
            ",\n      'backing_module' => '",
            Document::String(backing_module.to_string()),
            "'\n    }~",
        ]
    }

    /// Generates `register_class/0` for native facade — includes `native:` in `ClassBuilder` cascade.
    #[expect(
        clippy::too_many_lines,
        reason = "register_class codegen builds full BuilderState with metadata"
    )]
    fn generate_native_register_class(&mut self, module: &Module) -> Result<Document<'static>> {
        if module.classes.is_empty() {
            return Ok(Document::Nil);
        }

        let mut class_docs = Vec::new();

        for (i, class) in module.classes.iter().enumerate() {
            let backing_module = class
                .backing_module
                .as_deref()
                .expect("native facade requires backing_module");

            // Instance methods
            let instance_methods: Vec<_> = class
                .methods
                .iter()
                .filter(|m| m.kind == MethodKind::Primary)
                .collect();

            // Method source
            let mut method_source_docs: Vec<Document<'static>> = Vec::new();
            for (method_idx, method) in instance_methods.iter().enumerate() {
                if method_idx > 0 {
                    method_source_docs.push(Document::Str(", "));
                }
                let source_str = self.extract_method_source(method);
                let binary = Self::binary_string_literal(&source_str);
                method_source_docs.push(docvec![
                    "'",
                    Document::String(method.selector.name().to_string()),
                    "' => ",
                    Document::String(binary),
                ]);
            }
            let method_source_doc = Document::Vec(method_source_docs);

            // Method display signatures
            let mut method_sig_docs: Vec<Document<'static>> = Vec::new();
            for (method_idx, method) in instance_methods.iter().enumerate() {
                if method_idx > 0 {
                    method_sig_docs.push(Document::Str(", "));
                }
                let sig_str = unparse_method_display_signature(method);
                let binary = Self::binary_string_literal(&sig_str);
                method_sig_docs.push(docvec![
                    "'",
                    Document::String(method.selector.name().to_string()),
                    "' => ",
                    Document::String(binary),
                ]);
            }
            let method_sigs_doc = Document::Vec(method_sig_docs);

            // Class-side method display signatures
            let mut class_method_sig_docs: Vec<Document<'static>> = Vec::new();
            for (method_idx, method) in class
                .class_methods
                .iter()
                .filter(|m| m.kind == MethodKind::Primary)
                .enumerate()
            {
                if method_idx > 0 {
                    class_method_sig_docs.push(Document::Str(", "));
                }
                let sig_str = unparse_method_display_signature(method);
                let binary = Self::binary_string_literal(&sig_str);
                class_method_sig_docs.push(docvec![
                    "'",
                    Document::String(method.selector.name().to_string()),
                    "' => ",
                    Document::String(binary),
                ]);
            }
            let class_method_sigs_doc = Document::Vec(class_method_sig_docs);

            // Class variable initial values
            let mut class_var_parts: Vec<Document<'static>> = Vec::new();
            for (cv_idx, cv) in class.class_variables.iter().enumerate() {
                if cv_idx > 0 {
                    class_var_parts.push(Document::Str(", "));
                }
                let val = if let Some(ref default_value) = cv.default_value {
                    self.expression_doc(default_value)?
                } else {
                    Document::Str("'nil'")
                };
                class_var_parts.push(docvec![
                    "'",
                    Document::String(cv.name.name.to_string()),
                    "' => ",
                    val,
                ]);
            }
            let class_vars_doc = Document::Vec(class_var_parts);

            // Class-level doc comment
            let class_doc_value: Document<'static> = if let Some(ref doc) = class.doc_comment {
                Document::String(Self::binary_string_literal(doc))
            } else {
                Document::Str("'none'")
            };

            // Method-level doc comments
            let mut method_docs_parts: Vec<Document<'static>> = Vec::new();
            for method in &instance_methods {
                if let Some(ref doc) = method.doc_comment {
                    if !method_docs_parts.is_empty() {
                        method_docs_parts.push(Document::Str(", "));
                    }
                    let binary = Self::binary_string_literal(doc);
                    method_docs_parts.push(docvec![
                        "'",
                        Document::String(method.selector.name().to_string()),
                        "' => ",
                        Document::String(binary),
                    ]);
                }
            }
            let method_docs_doc = Document::Vec(method_docs_parts);

            // Native actors are not constructible via new
            let class_doc = docvec![
                line(),
                "let _BuilderState",
                i,
                " = ~{",
                nest(
                    INDENT,
                    docvec![
                        line(),
                        docvec![
                            "'className' => '",
                            Document::String(class.name.name.to_string()),
                            "',"
                        ],
                        line(),
                        docvec![
                            "'superclassRef' => '",
                            Document::String(class.superclass_name().to_string()),
                            "',"
                        ],
                        line(),
                        docvec![
                            "'moduleName' => '",
                            Document::String(self.module_name.clone()),
                            "',"
                        ],
                        line(),
                        "'methodSource' => ~{",
                        method_source_doc,
                        "}~,",
                        line(),
                        "'methodSignatures' => ~{",
                        method_sigs_doc,
                        "}~,",
                        line(),
                        "'classMethodSignatures' => ~{",
                        class_method_sigs_doc,
                        "}~,",
                        line(),
                        "'classState' => ~{",
                        class_vars_doc,
                        "}~,",
                        line(),
                        "'classDoc' => ",
                        class_doc_value,
                        ",",
                        line(),
                        "'methodDocs' => ~{",
                        method_docs_doc,
                        "}~,",
                        line(),
                        "'meta' => ",
                        Self::build_native_meta_map_doc(class, module, backing_module),
                        ",",
                        line(),
                        "'isConstructible' => 'false'",
                        if self.stdlib_mode {
                            docvec![",", line(), "'stdlibMode' => 'true'"]
                        } else {
                            Document::Nil
                        },
                    ]
                ),
                line(),
                "}~",
                line(),
                "in let _Reg",
                i,
                " = case call 'beamtalk_class_builder':'register'(_BuilderState",
                i,
                ") of",
                nest(
                    INDENT,
                    docvec![
                        line(),
                        "<{'ok', _Pid",
                        i,
                        "}> when 'true' -> 'ok'",
                        line(),
                        "<{'error', _Err",
                        i,
                        "}> when 'true' -> {'error', _Err",
                        i,
                        "}",
                    ]
                ),
                line(),
                "end",
            ];
            class_docs.push(class_doc);
        }

        // Build short-circuit chain (same pattern as regular register_class)
        let last_i = class_docs.len() - 1;
        let mut try_body: Document<'static> =
            docvec![class_docs[last_i].clone(), "\n", line(), "in _Reg", last_i,];
        for i in (0..last_i).rev() {
            try_body = docvec![
                class_docs[i].clone(),
                "\n",
                line(),
                "in case _Reg",
                i,
                " of",
                nest(
                    INDENT,
                    docvec![
                        line(),
                        "<{'error', _RegErr",
                        i,
                        "}> when 'true' -> {'error', _RegErr",
                        i,
                        "}",
                        line(),
                        "<_> when 'true' ->",
                        nest(INDENT, docvec![line(), try_body]),
                    ]
                ),
                line(),
                "end",
            ];
        }

        let doc = docvec![
            "'register_class'/0 = fun () ->",
            nest(
                INDENT,
                docvec![line(), "try", nest(INDENT, docvec![try_body, "\n",]),]
            ),
            nest(
                INDENT,
                docvec![
                    line(),
                    "of RegResult -> RegResult",
                    line(),
                    "catch <CatchType, CatchError, CatchStack> -> primop 'raw_raise'(CatchType, CatchError, CatchStack)",
                ]
            ),
            "\n\n",
        ];

        Ok(doc)
    }
}
