#!/usr/bin/env bash
# Copyright 2026 James Casey
# SPDX-License-Identifier: Apache-2.0
#
# PreToolUse hook: block edits to generated/build-output files.
#
# Exit 0  → allow the edit to proceed.
# Exit 2  → block the edit; stdout is shown to Claude as the reason.

set -uo pipefail

INPUT=$(cat)
FILE_PATH=$(python3 -c "
import sys, json
d = json.load(sys.stdin)
print(d.get('tool_input', {}).get('file_path', ''))
" <<< "$INPUT" 2>/dev/null || true)

[[ -z "$FILE_PATH" ]] && exit 0

# Normalise to a relative path for pattern matching.
PROJ="${CLAUDE_PROJECT_DIR:-$(pwd)}"
REL="${FILE_PATH#"$PROJ"/}"

block() {
  echo "BLOCKED — $1"
  echo "Edit the generator or source instead:"
  echo "  $2"
  exit 2
}

case "$REL" in
  # beamtalk_stdlib.app.src is written by `beamtalk build-stdlib` (build_stdlib.rs).
  runtime/apps/beamtalk_stdlib/src/beamtalk_stdlib.app.src)
    block \
      "'beamtalk_stdlib.app.src' is generated by build_stdlib.rs — manual edits are overwritten on every build." \
      "crates/beamtalk-cli/src/commands/build_stdlib.rs (see generate_app_src fn)"
    ;;

  # Anything inside _build/ is BEAM compiler output.
  _build/*)
    block \
      "'$REL' is inside _build/ which is compiler output." \
      "Edit the corresponding source file in runtime/apps/ or stdlib/src/ instead."
    ;;

  # Compiled .beam / .core artefacts anywhere.
  *.beam|*.core)
    block \
      "'$(basename "$FILE_PATH")' is a compiled BEAM artefact — it cannot be hand-edited." \
      "Edit the corresponding .erl or .bt source file."
    ;;
esac

exit 0
