%% Copyright 2026 James Casey
%% SPDX-License-Identifier: Apache-2.0

-module(beamtalk_class_direct_dispatch_tests).

%%% **DDD Context:** Object System Context

-moduledoc """
EUnit tests for direct dispatch of dynamic class-side sends (ADR 0129 Phase 0b,
BT-3639).

`beamtalk_class_dispatch:class_send/3` consults the class's
`direct_class_methods` (generated by Rust's `compute_direct_call_eligible`,
cached in the unified metadata row) and calls `Module:SafeFn(nil, #{}, Args...)`
in the caller for listed selectors; everything else takes the gen_server path.
""".

-include_lib("eunit/include/eunit.hrl").

-define(HELPER, beamtalk_class_dispatch_test_helper).

setup() ->
    {ok, _} = application:ensure_all_started(beamtalk_runtime),
    ok = beamtalk_stdlib:init(),
    ok.

start_class(Name, Meta) ->
    ClassInfo = #{
        superclass => none,
        module => ?HELPER,
        class_methods => #{testSelf => #{arity => 0}},
        class_state => #{},
        meta => Meta
    },
    {ok, Pid} = beamtalk_object_class:start_link(Name, ClassInfo),
    unlink(Pid),
    Pid.

stop_class(Pid) ->
    catch gen_server:stop(Pid, normal, 5000),
    ok.

direct_dispatch_test_() ->
    {setup, fun setup/0, fun(_) -> ok end, [
        {"eligible selector runs in the caller's process", fun() ->
            Pid = start_class('BT3639Direct', #{
                direct_class_methods => #{testSelf => class_testSelf}
            }),
            try
                ?assertEqual(self(), beamtalk_class_dispatch:class_send(Pid, testSelf, []))
            after
                stop_class(Pid)
            end
        end},
        {"selector absent from the set goes through the class gen_server", fun() ->
            Pid = start_class('BT3639Gated', #{direct_class_methods => #{}}),
            try
                ?assertEqual(Pid, beamtalk_class_dispatch:class_send(Pid, testSelf, []))
            after
                stop_class(Pid)
            end
        end},
        {"meta without the key never dispatches directly", fun() ->
            Pid = start_class('BT3639NoKey', #{}),
            try
                ?assertEqual(Pid, beamtalk_class_dispatch:class_send(Pid, testSelf, []))
            after
                stop_class(Pid)
            end
        end},
        {"arity mismatch is not called directly", fun() ->
            Pid = start_class('BT3639Arity', #{
                direct_class_methods => #{testSelf => class_testSelf}
            }),
            try
                %% class_testSelf/2 does not exist: the direct path must decline
                %% and leave the error to the gen_server path.
                ?assertEqual(
                    error, beamtalk_class_dispatch:lookup_direct_call(Pid, testSelf, [1])
                )
            after
                stop_class(Pid)
            end
        end},
        {"reload with a changed eligibility set updates dispatch", fun() ->
            Pid = start_class('BT3639Reload', #{
                direct_class_methods => #{testSelf => class_testSelf}
            }),
            try
                ?assertEqual(self(), beamtalk_class_dispatch:class_send(Pid, testSelf, [])),
                {ok, _} = beamtalk_object_class:update_class('BT3639Reload', #{
                    module => ?HELPER, meta => #{direct_class_methods => #{}}
                }),
                ?assertEqual(Pid, beamtalk_class_dispatch:class_send(Pid, testSelf, [])),
                {ok, _} = beamtalk_object_class:update_class('BT3639Reload', #{
                    module => ?HELPER,
                    meta => #{direct_class_methods => #{testSelf => class_testSelf}}
                }),
                ?assertEqual(self(), beamtalk_class_dispatch:class_send(Pid, testSelf, []))
            after
                stop_class(Pid)
            end
        end},
        {"runtime class-method funs disable the direct path", fun() ->
            Pid = start_class('BT3639Funs', #{direct_class_methods => #{testSelf => class_testSelf}}),
            try
                beamtalk_class_metadata:set_runtime_class_methods('BT3639Funs', [testSelf]),
                ?assertEqual(
                    error,
                    beamtalk_class_metadata:lookup_direct_class_method('BT3639Funs', testSelf)
                )
            after
                stop_class(Pid)
            end
        end}
    ]}.
