%% AUTO-GENERATED by `beamtalk build-stdlib` from crates/beamtalk-codegen/src/core_erlang/class_var_keys.rs — do not edit manually.
%% Copyright 2026 James Casey
%% SPDX-License-Identifier: Apache-2.0

%% The class-variable process-dictionary key shape (ADR 0130 §1, §2), shared
%% with the inlined class-variable reads and writes codegen emits.
%% Regenerate with `just build-stdlib`; `just check-generated-builtins` fails
%% when this file is stale.

-ifndef(BEAMTALK_CLASS_VARS_KEYS_HRL).
-define(BEAMTALK_CLASS_VARS_KEYS_HRL, true).

%% The key of a class's variables; `ClassTag` is the metaclass tag
%% (`'Name class'`, `element(2, ClassSelf)`).
-define(BT_CLASS_VARS_KEY(ClassTag), {'$bt_class_vars', ClassTag}).

%% The process-dictionary key naming the live invocation's class key.
-define(BT_CLASS_VARS_HOME, '$bt_class_vars_home').

%% The read-only marker planted under a class key by `with_snapshot/2`.
-define(BT_CLASS_VARS_RO(ClassTag), {'$bt_class_vars_ro', ClassTag}).

%% The `class_var_abi` value compiled modules declare in `__beamtalk_meta/0`.
-define(BT_CLASS_VAR_ABI, 1).

-endif.
