// AUTO-GENERATED from lib/*.bt by `beamtalk build-stdlib` — do not edit manually.
// Copyright 2026 James Casey
// SPDX-License-Identifier: Apache-2.0

//! Generated built-in class definitions derived from `lib/*.bt` stdlib sources.
//!
//! This file is regenerated by `beamtalk build-stdlib`. Any manual edits
//! will be overwritten on the next build.

use super::super::{ClassInfo, MethodInfo};
use crate::ast::MethodKind;
use ecow::EcoString;
use std::collections::HashMap;

/// Returns true if the given class name is a stdlib built-in class.
///
/// Auto-generated from `lib/*.bt` file names.
pub(super) fn is_generated_builtin_class(name: &str) -> bool {
    matches!(
        name,
        "Actor"
            | "Association"
            | "Block"
            | "Boolean"
            | "Character"
            | "Collection"
            | "CompiledMethod"
            | "Dictionary"
            | "Error"
            | "Exception"
            | "False"
            | "File"
            | "Float"
            | "InstantiationError"
            | "Integer"
            | "List"
            | "Number"
            | "Object"
            | "ProtoObject"
            | "RuntimeError"
            | "Set"
            | "StackFrame"
            | "Stream"
            | "String"
            | "Symbol"
            | "SystemDictionary"
            | "TestCase"
            | "TranscriptStream"
            | "True"
            | "Tuple"
            | "TypeError"
            | "UndefinedObject"
            | "WorkspaceEnvironment"
    )
}

/// Returns all stdlib built-in class definitions.
///
/// Auto-generated from parsed `lib/*.bt` ASTs.
#[allow(clippy::too_many_lines)] // auto-generated from 32 stdlib classes
#[rustfmt::skip] // preserve compact generated layout
pub(super) fn generated_builtin_classes() -> HashMap<EcoString, ClassInfo> {
    let mut classes = HashMap::new();

    classes.insert(
        "Actor".into(),
        ClassInfo {
            name: "Actor".into(),
            superclass: Some("Object".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "spawn".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Actor".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "spawnWith:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Actor".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "new".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Actor".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "new:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Actor".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Actor".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Association".into(),
        ClassInfo {
            name: "Association".into(),
            superclass: Some("Object".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "key".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Association".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "value".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Association".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Association".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Association".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Association".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Block".into(),
        ClassInfo {
            name: "Block".into(),
            superclass: Some("Object".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "value".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Block".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "value:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Block".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "value:value:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Block".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "value:value:value:".into(), arity: 3, kind: MethodKind::Primary, defined_in: "Block".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "whileTrue:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Block".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "whileFalse:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Block".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "repeat".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Block".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "on:do:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Block".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ensure:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Block".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "arity".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Block".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "valueWithArguments:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Block".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Block".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Boolean".into(),
        ClassInfo {
            name: "Boolean".into(),
            superclass: Some("Object".into()),
            is_sealed: false,
            is_abstract: true,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "ifTrue:ifFalse:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Boolean".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifTrue:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Boolean".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifFalse:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Boolean".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "not".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Boolean".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isBoolean".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Boolean".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "and:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Boolean".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "or:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Boolean".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "xor:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Boolean".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Character".into(),
        ClassInfo {
            name: "Character".into(),
            superclass: Some("Object".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "=:=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "/=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "<".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: ">".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "<=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: ">=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asInteger".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "hash".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isLetter".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isDigit".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isUppercase".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isLowercase".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isWhitespace".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "uppercase".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "lowercase".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![
                MethodInfo { selector: "value:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Character".into(), is_sealed: true, return_type: None },
            ],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Collection".into(),
        ClassInfo {
            name: "Collection".into(),
            superclass: Some("Object".into()),
            is_sealed: false,
            is_abstract: true,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "size".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "do:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isEmpty".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isNotEmpty".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "includes:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "inject:into:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "collect:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "select:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "reject:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "detect:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "detect:ifNone:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "anySatisfy:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "allSatisfy:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Collection".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "CompiledMethod".into(),
        ClassInfo {
            name: "CompiledMethod".into(),
            superclass: Some("Object".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "selector".into(), arity: 0, kind: MethodKind::Primary, defined_in: "CompiledMethod".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "source".into(), arity: 0, kind: MethodKind::Primary, defined_in: "CompiledMethod".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "argumentCount".into(), arity: 0, kind: MethodKind::Primary, defined_in: "CompiledMethod".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "CompiledMethod".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "CompiledMethod".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Dictionary".into(),
        ClassInfo {
            name: "Dictionary".into(),
            superclass: Some("Collection".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "size".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "keys".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "values".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "at:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "at:ifAbsent:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "at:put:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "includesKey:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "removeKey:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "merge:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "includes:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "do:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "keysAndValuesDo:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "stream".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Dictionary".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Error".into(),
        ClassInfo {
            name: "Error".into(),
            superclass: Some("Exception".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Error".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Exception".into(),
        ClassInfo {
            name: "Exception".into(),
            superclass: Some("Object".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "message".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Exception".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "hint".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Exception".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "kind".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Exception".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "selector".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Exception".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "errorClass".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Exception".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Exception".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "stackTrace".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Exception".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Exception".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "signal".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Exception".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "signal:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Exception".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "False".into(),
        ClassInfo {
            name: "False".into(),
            superclass: Some("Boolean".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "ifTrue:ifFalse:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "False".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifTrue:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "False".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifFalse:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "False".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "not".into(), arity: 0, kind: MethodKind::Primary, defined_in: "False".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isTrue".into(), arity: 0, kind: MethodKind::Primary, defined_in: "False".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isFalse".into(), arity: 0, kind: MethodKind::Primary, defined_in: "False".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "False".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "False".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "File".into(),
        ClassInfo {
            name: "File".into(),
            superclass: Some("Object".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![],
            class_methods: vec![
                MethodInfo { selector: "exists:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "File".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "readAll:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "File".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "writeAll:contents:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "File".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "lines:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "File".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "open:do:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "File".into(), is_sealed: true, return_type: None },
            ],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Float".into(),
        ClassInfo {
            name: "Float".into(),
            superclass: Some("Number".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "+".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "-".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "*".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "/".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "=:=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "/=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "<".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: ">".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "<=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: ">=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "negated".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "abs".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "min:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "max:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "rounded".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ceiling".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "floor".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "truncated".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isNaN".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isInfinite".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isZero".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asInteger".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Float".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "InstantiationError".into(),
        ClassInfo {
            name: "InstantiationError".into(),
            superclass: Some("Error".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "InstantiationError".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Integer".into(),
        ClassInfo {
            name: "Integer".into(),
            superclass: Some("Number".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "+".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "-".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "*".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "/".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "div:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "%".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "**".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "=:=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "/=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "<".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: ">".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "<=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: ">=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "negated".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "abs".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isEven".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isOdd".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "min:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "max:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "timesRepeat:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "to:do:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "to:by:do:".into(), arity: 3, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asFloat".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "bitAnd:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "bitOr:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "bitXor:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "bitShift:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "bitNot".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "factorial".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "gcd:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "lcm:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isLetter".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isDigit".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isUppercase".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isLowercase".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isWhitespace".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Integer".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "List".into(),
        ClassInfo {
            name: "List".into(),
            superclass: Some("Collection".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "size".into(), arity: 0, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isEmpty".into(), arity: 0, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "first".into(), arity: 0, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "rest".into(), arity: 0, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "last".into(), arity: 0, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "at:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "includes:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "sort".into(), arity: 0, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "sort:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "reversed".into(), arity: 0, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "unique".into(), arity: 0, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "detect:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "detect:ifNone:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "do:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "collect:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "select:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "reject:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "inject:into:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "take:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "drop:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "flatten".into(), arity: 0, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "flatMap:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "count:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "anySatisfy:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "allSatisfy:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "++".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "from:to:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "indexOf:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "eachWithIndex:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "zip:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "groupBy:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "partition:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "takeWhile:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "dropWhile:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "intersperse:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "add:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "stream".into(), arity: 0, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "List".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Number".into(),
        ClassInfo {
            name: "Number".into(),
            superclass: Some("Object".into()),
            is_sealed: false,
            is_abstract: true,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "=:=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Number".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "<".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Number".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: ">".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Number".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "<=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Number".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: ">=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Number".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isZero".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Number".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isPositive".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Number".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isNegative".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Number".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "sign".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Number".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "between:and:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Number".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Object".into(),
        ClassInfo {
            name: "Object".into(),
            superclass: Some("ProtoObject".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "class".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "new".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "new:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isNil".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "notNil".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifNil:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifNotNil:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifNil:ifNotNil:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifNotNil:ifNil:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "inspect".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "yourself".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "hash".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "respondsTo:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "instVarNames".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "instVarAt:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "instVarAt:put:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "perform:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "perform:withArguments:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "->".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "subclassResponsibility".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "error:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Object".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "ProtoObject".into(),
        ClassInfo {
            name: "ProtoObject".into(),
            superclass: None,
            is_sealed: false,
            is_abstract: true,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "==".into(), arity: 1, kind: MethodKind::Primary, defined_in: "ProtoObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "/=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "ProtoObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "class".into(), arity: 0, kind: MethodKind::Primary, defined_in: "ProtoObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "doesNotUnderstand:args:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "ProtoObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "perform:withArguments:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "ProtoObject".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "RuntimeError".into(),
        ClassInfo {
            name: "RuntimeError".into(),
            superclass: Some("Error".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "RuntimeError".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Set".into(),
        ClassInfo {
            name: "Set".into(),
            superclass: Some("Collection".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec!["elements".into()],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "size".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isEmpty".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "includes:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "add:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "remove:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "union:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "intersection:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "difference:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isSubsetOf:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asList".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "fromList:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "do:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "stream".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Set".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "StackFrame".into(),
        ClassInfo {
            name: "StackFrame".into(),
            superclass: Some("Object".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "method".into(), arity: 0, kind: MethodKind::Primary, defined_in: "StackFrame".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "receiverClass".into(), arity: 0, kind: MethodKind::Primary, defined_in: "StackFrame".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "arguments".into(), arity: 0, kind: MethodKind::Primary, defined_in: "StackFrame".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "sourceLocation".into(), arity: 0, kind: MethodKind::Primary, defined_in: "StackFrame".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "moduleName".into(), arity: 0, kind: MethodKind::Primary, defined_in: "StackFrame".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "line".into(), arity: 0, kind: MethodKind::Primary, defined_in: "StackFrame".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "file".into(), arity: 0, kind: MethodKind::Primary, defined_in: "StackFrame".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "StackFrame".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Stream".into(),
        ClassInfo {
            name: "Stream".into(),
            superclass: Some("Object".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "select:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "collect:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "reject:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "drop:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "take:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "do:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "inject:into:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "detect:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asList".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "anySatisfy:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "allSatisfy:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![
                MethodInfo { selector: "from:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "from:by:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: true, return_type: None },
                MethodInfo { selector: "on:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Stream".into(), is_sealed: true, return_type: None },
            ],
            class_variables: vec![],
        },
    );

    classes.insert(
        "String".into(),
        ClassInfo {
            name: "String".into(),
            superclass: Some("Object".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "=:=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "/=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "<".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: ">".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "<=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: ">=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "++".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "length".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "size".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "at:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "uppercase".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "lowercase".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "capitalize".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "trim".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "trimLeft".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "trimRight".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "reverse".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "includes:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "startsWith:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "endsWith:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "indexOf:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "split:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "splitOn:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "repeat:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "lines".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "words".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "replaceAll:with:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "replaceFirst:with:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "take:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "drop:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "padLeft:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "padRight:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "padLeft:with:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "padRight:with:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isEmpty".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isNotEmpty".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isBlank".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isDigit".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isAlpha".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asInteger".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asFloat".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asAtom".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asList".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "each:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "collect:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "select:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "stream".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "String".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Symbol".into(),
        ClassInfo {
            name: "Symbol".into(),
            superclass: Some("Object".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "asString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Symbol".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asAtom".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Symbol".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Symbol".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Symbol".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "=:=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Symbol".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "/=".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Symbol".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "hash".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Symbol".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "SystemDictionary".into(),
        ClassInfo {
            name: "SystemDictionary".into(),
            superclass: Some("Actor".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "allClasses".into(), arity: 0, kind: MethodKind::Primary, defined_in: "SystemDictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "classNamed:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "SystemDictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "globals".into(), arity: 0, kind: MethodKind::Primary, defined_in: "SystemDictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "version".into(), arity: 0, kind: MethodKind::Primary, defined_in: "SystemDictionary".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![
                MethodInfo { selector: "current".into(), arity: 0, kind: MethodKind::Primary, defined_in: "SystemDictionary".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "current:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "SystemDictionary".into(), is_sealed: false, return_type: None },
            ],
            class_variables: vec!["current".into()],
        },
    );

    classes.insert(
        "TestCase".into(),
        ClassInfo {
            name: "TestCase".into(),
            superclass: Some("Object".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "setUp".into(), arity: 0, kind: MethodKind::Primary, defined_in: "TestCase".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "tearDown".into(), arity: 0, kind: MethodKind::Primary, defined_in: "TestCase".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "assert:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "TestCase".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "assert:equals:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "TestCase".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "deny:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "TestCase".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "should:raise:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "TestCase".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "fail:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "TestCase".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![
                MethodInfo { selector: "runAll".into(), arity: 0, kind: MethodKind::Primary, defined_in: "TestCase".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "run:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "TestCase".into(), is_sealed: false, return_type: None },
            ],
            class_variables: vec![],
        },
    );

    classes.insert(
        "TranscriptStream".into(),
        ClassInfo {
            name: "TranscriptStream".into(),
            superclass: Some("Actor".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "show:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "TranscriptStream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "cr".into(), arity: 0, kind: MethodKind::Primary, defined_in: "TranscriptStream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "subscribe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "TranscriptStream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "unsubscribe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "TranscriptStream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "recent".into(), arity: 0, kind: MethodKind::Primary, defined_in: "TranscriptStream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "clear".into(), arity: 0, kind: MethodKind::Primary, defined_in: "TranscriptStream".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![
                MethodInfo { selector: "current".into(), arity: 0, kind: MethodKind::Primary, defined_in: "TranscriptStream".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "current:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "TranscriptStream".into(), is_sealed: false, return_type: None },
            ],
            class_variables: vec!["current".into()],
        },
    );

    classes.insert(
        "True".into(),
        ClassInfo {
            name: "True".into(),
            superclass: Some("Boolean".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "ifTrue:ifFalse:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "True".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifTrue:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "True".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifFalse:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "True".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "not".into(), arity: 0, kind: MethodKind::Primary, defined_in: "True".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isTrue".into(), arity: 0, kind: MethodKind::Primary, defined_in: "True".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isFalse".into(), arity: 0, kind: MethodKind::Primary, defined_in: "True".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "True".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "True".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "Tuple".into(),
        ClassInfo {
            name: "Tuple".into(),
            superclass: Some("Collection".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "size".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Tuple".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "at:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Tuple".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isOk".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Tuple".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "isError".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Tuple".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "unwrap".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Tuple".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "unwrapOr:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Tuple".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "unwrapOrElse:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Tuple".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "asString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Tuple".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "Tuple".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "do:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "Tuple".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "TypeError".into(),
        ClassInfo {
            name: "TypeError".into(),
            superclass: Some("Error".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "TypeError".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "UndefinedObject".into(),
        ClassInfo {
            name: "UndefinedObject".into(),
            superclass: Some("Object".into()),
            is_sealed: true,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "isNil".into(), arity: 0, kind: MethodKind::Primary, defined_in: "UndefinedObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "notNil".into(), arity: 0, kind: MethodKind::Primary, defined_in: "UndefinedObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifNil:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "UndefinedObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifNotNil:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "UndefinedObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifNil:ifNotNil:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "UndefinedObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "ifNotNil:ifNil:".into(), arity: 2, kind: MethodKind::Primary, defined_in: "UndefinedObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "copy".into(), arity: 0, kind: MethodKind::Primary, defined_in: "UndefinedObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "deepCopy".into(), arity: 0, kind: MethodKind::Primary, defined_in: "UndefinedObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "shallowCopy".into(), arity: 0, kind: MethodKind::Primary, defined_in: "UndefinedObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "describe".into(), arity: 0, kind: MethodKind::Primary, defined_in: "UndefinedObject".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "printString".into(), arity: 0, kind: MethodKind::Primary, defined_in: "UndefinedObject".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![],
            class_variables: vec![],
        },
    );

    classes.insert(
        "WorkspaceEnvironment".into(),
        ClassInfo {
            name: "WorkspaceEnvironment".into(),
            superclass: Some("Actor".into()),
            is_sealed: false,
            is_abstract: false,
            is_typed: false,
            state: vec![],
            state_types: HashMap::new(),
            methods: vec![
                MethodInfo { selector: "actors".into(), arity: 0, kind: MethodKind::Primary, defined_in: "WorkspaceEnvironment".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "actorAt:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "WorkspaceEnvironment".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "actorsOf:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "WorkspaceEnvironment".into(), is_sealed: false, return_type: None },
            ],
            class_methods: vec![
                MethodInfo { selector: "current".into(), arity: 0, kind: MethodKind::Primary, defined_in: "WorkspaceEnvironment".into(), is_sealed: false, return_type: None },
                MethodInfo { selector: "current:".into(), arity: 1, kind: MethodKind::Primary, defined_in: "WorkspaceEnvironment".into(), is_sealed: false, return_type: None },
            ],
            class_variables: vec!["current".into()],
        },
    );

    classes
}
