@echo off
setlocal enabledelayedexpansion
rem Copyright 2026 James Casey
rem SPDX-License-Identifier: Apache-2.0
rem
rem Generated by `beamtalk release` — ADR 0125 §1.6/§1.7/§0027 (BT-3573). Do
rem not edit; it is overwritten on every `beamtalk release`.
rem
rem Verbs: foreground (default) ^| stop ^| ping ^| remote_console ^| eval ^| rpc ^| version

set "RELEASE_NAME=__RELEASE_NAME__"
set "RELEASE_VSN=__RELEASE_VSN__"
set "ERTS_VSN=__ERTS_VERSION__"
set "INCLUDE_ERTS=__INCLUDE_ERTS__"

set "SCRIPT_DIR=%~dp0"
for %%I in ("%SCRIPT_DIR%..") do set "ROOT=%%~fI"
set "CONFIG_DIR=%ROOT%\releases\%RELEASE_VSN%"
set "PROVENANCE=%CONFIG_DIR%\beamtalk-provenance.json"

rem Resolve the erl.exe to run: bundled ERTS when present (the default), else
rem the host erl.exe on PATH (ADR 0125 §1.3/§3.2).
set "USING_HOST_ERTS=false"
set "ERL="
if /I "%INCLUDE_ERTS%"=="true" if exist "%ROOT%\erts-%ERTS_VSN%\bin\erl.exe" set "ERL=%ROOT%\erts-%ERTS_VSN%\bin\erl.exe"
if not defined ERL (
    for %%E in (erl.exe) do set "ERL=%%~$PATH:E"
    set "USING_HOST_ERTS=true"
)
if not defined ERL (
    echo error: no Erlang/OTP found — no bundled ERTS in "%ROOT%", and erl.exe is not on PATH 1>&2
    exit /b 1
)

rem Pin epmd to loopback (ADR 0125 §1.6) for every verb that can start
rem distribution or epmd itself — see launcher.sh's identical comment.
set "ERL_EPMD_ADDRESS=127.0.0.1"

set "VERB=%~1"
if "%VERB%"=="" set "VERB=foreground"
if not "%VERB%"=="" shift

if /I "%VERB%"=="foreground" goto :foreground
if /I "%VERB%"=="stop" goto :stop
if /I "%VERB%"=="ping" goto :ping
if /I "%VERB%"=="remote_console" goto :remote_console
if /I "%VERB%"=="eval" goto :eval
if /I "%VERB%"=="rpc" goto :rpc
if /I "%VERB%"=="version" goto :version
goto :usage

:check_otp_window
if /I not "%USING_HOST_ERTS%"=="true" exit /b 0
if not exist "%PROVENANCE%" exit /b 0
set "REQ_MIN="
set "REQ_MAX="
set "BUILT_OTP="
for /f "tokens=2 delims=:," %%A in ('findstr /c:"\"min\"" "%PROVENANCE%"') do set "REQ_MIN=%%~A"
for /f "tokens=2 delims=:," %%A in ('findstr /c:"\"max\"" "%PROVENANCE%"') do set "REQ_MAX=%%~A"
for /f "tokens=2 delims=:" %%A in ('findstr /c:"\"otp_release\"" "%PROVENANCE%"') do set "BUILT_OTP=%%~A"
set "REQ_MIN=%REQ_MIN: =%"
set "REQ_MAX=%REQ_MAX: =%"
set "BUILT_OTP=%BUILT_OTP:"=%"
set "BUILT_OTP=%BUILT_OTP:,=%"
set "BUILT_OTP=%BUILT_OTP: =%"
for /f "tokens=1 delims=-" %%A in ("%BUILT_OTP%") do set "BUILT_MAJOR=%%A"
if not defined REQ_MIN exit /b 0
if not defined REQ_MAX exit /b 0
set "HOST_MAJOR="
rem The extra outer quote pair around the whole inner command is required:
rem this command starts with a quoted "%ERL%" and contains more than two
rem `"` characters overall, which trips a documented `cmd.exe /c` quirk
rem (see `cmd /?`) where, unless a command line has *exactly* two quote
rem characters, cmd strips the *first and last* quote of the entire line
rem instead of preserving it — silently mangling this call so it produces
rem no output, leaving HOST_MAJOR unset and the OTP-window check a no-op.
rem Wrapping the command in one more quote pair makes that bogus strip
rem remove the added quotes instead, leaving the real ones intact.
for /f "delims=" %%A in ('""%ERL%" -noshell -eval "io:format(\"~s\", [erlang:system_info(otp_release)]), halt()." 2^>nul"') do set "HOST_MAJOR=%%A"
if not defined HOST_MAJOR exit /b 0
if %HOST_MAJOR% LSS %REQ_MIN% goto :otp_window_fail
if %HOST_MAJOR% GTR %REQ_MAX% goto :otp_window_fail
exit /b 0
:otp_window_fail
echo %RELEASE_NAME% %RELEASE_VSN% cannot start on Erlang/OTP %HOST_MAJOR%. 1>&2
echo. 1>&2
echo   This release's BEAM files were produced by OTP %BUILT_MAJOR% and will not load on 1>&2
echo   an older VM. 1>&2
echo. 1>&2
echo   Required: Erlang/OTP %REQ_MIN%-%REQ_MAX% (built on %BUILT_MAJOR%) 1>&2
echo   Found:    Erlang/OTP %HOST_MAJOR% (%ERL%) 1>&2
echo. 1>&2
echo   Either install a supported Erlang/OTP version, or rebuild the release on this host. 1>&2
exit /b 1

:lib_pa_args
set "PA_ARGS="
for /d %%D in ("%ROOT%\lib\*") do (
    if exist "%%D\ebin" set "PA_ARGS=!PA_ARGS! -pa "%%D\ebin""
)
exit /b 0

:cookie_args
set "COOKIE_ARGS="
if defined RELEASE_COOKIE set "COOKIE_ARGS=-setcookie %RELEASE_COOKIE%"
exit /b 0

rem `-boot` for every verb below except `foreground` — see launcher.sh's
rem `minimal_boot_args` comment: with no `-boot`, erl.exe falls back to
rem `%ROOT%\bin\start.boot`, which does not exist; `copy_erts` stages a
rem plain kernel+stdlib `start_clean.boot` next to the bundled ERTS for
rem exactly this. A host ERTS already has its own default boot file.
:minimal_boot_args
set "BOOT_ARGS="
if /I "%INCLUDE_ERTS%"=="true" if exist "%ROOT%\erts-%ERTS_VSN%\bin\start_clean.boot" (
    set "BOOT_ARGS=-boot "%ROOT%\erts-%ERTS_VSN%\bin\start_clean""
)
exit /b 0

:foreground
call :check_otp_window
if errorlevel 1 exit /b 1
call :cookie_args
rem -noshell -noinput: see launcher.sh's foreground comment — no
rem interactive shell attaches stdin, so a supervisor with no tty
rem (a Windows service, a container) does not make the node see EOF
rem and terminate right after boot. Console output is unaffected.
"%ERL%" -noshell -noinput -boot "%CONFIG_DIR%\start" -boot_var RELEASE_DIR "%ROOT%" ^
    -config "%CONFIG_DIR%\sys" -args_file "%CONFIG_DIR%\vm.args" %COOKIE_ARGS%
exit /b %errorlevel%

:stop
call :check_otp_window
if errorlevel 1 exit /b 1
call :lib_pa_args
call :cookie_args
call :minimal_boot_args
set "SNAME=%RELEASE_NAME%_stop_%RANDOM%"
rem @localhost, not %COMPUTERNAME% — see launcher.sh's identical comment.
set "NODE=%RELEASE_NAME%@localhost"
"%ERL%" -noshell -hidden -sname "%SNAME%" %COOKIE_ARGS% %BOOT_ARGS% %PA_ARGS% ^
    -eval "beamtalk_release_launcher:stop_client_main()." -extra "%NODE%"
exit /b %errorlevel%

:ping
call :check_otp_window
if errorlevel 1 exit /b 1
call :lib_pa_args
call :cookie_args
call :minimal_boot_args
set "SNAME=%RELEASE_NAME%_ping_%RANDOM%"
rem @localhost, not %COMPUTERNAME% — see launcher.sh's identical comment.
set "NODE=%RELEASE_NAME%@localhost"
"%ERL%" -noshell -hidden -sname "%SNAME%" %COOKIE_ARGS% %BOOT_ARGS% %PA_ARGS% ^
    -eval "beamtalk_release_launcher:ping_client_main()." -extra "%NODE%"
exit /b %errorlevel%

:remote_console
call :check_otp_window
if errorlevel 1 exit /b 1
call :cookie_args
call :minimal_boot_args
set "SNAME=%RELEASE_NAME%_rc_%RANDOM%"
rem @localhost, not %COMPUTERNAME% — see launcher.sh's identical comment.
set "NODE=%RELEASE_NAME%@localhost"
"%ERL%" -hidden -sname "%SNAME%" %COOKIE_ARGS% %BOOT_ARGS% -remsh "%NODE%"
exit /b %errorlevel%

:eval
call :check_otp_window
if errorlevel 1 exit /b 1
if "%~1"=="" goto :usage
set "ENTRY=%~1"
for /f "tokens=1,2,*" %%A in ("%ENTRY%") do (
    set "CLASS=%%A"
    set "SELECTOR=%%B"
    set "ENTRY_REST=%%C"
)
if not defined CLASS goto :usage
if not defined SELECTOR goto :usage
call :lib_pa_args
call :minimal_boot_args
"%ERL%" -noshell %BOOT_ARGS% %PA_ARGS% ^
    -config "%CONFIG_DIR%\sys" -beamtalk_workspace console false ^
    -eval "beamtalk_release_launcher:eval_main()." ^
    -extra "%CLASS%" "%SELECTOR%" %ENTRY_REST%
exit /b %errorlevel%

:rpc
call :check_otp_window
if errorlevel 1 exit /b 1
if "%~1"=="" goto :usage
set "ENTRY=%~1"
for /f "tokens=1,2,*" %%A in ("%ENTRY%") do (
    set "CLASS=%%A"
    set "SELECTOR=%%B"
    set "ENTRY_REST=%%C"
)
if not defined CLASS goto :usage
if not defined SELECTOR goto :usage
call :lib_pa_args
call :cookie_args
call :minimal_boot_args
set "SNAME=%RELEASE_NAME%_rpc_%RANDOM%"
rem @localhost, not %COMPUTERNAME% — see launcher.sh's identical comment.
set "NODE=%RELEASE_NAME%@localhost"
"%ERL%" -noshell -hidden -sname "%SNAME%" %COOKIE_ARGS% %BOOT_ARGS% %PA_ARGS% ^
    -eval "beamtalk_release_launcher:rpc_client_main()." ^
    -extra "%NODE%" "%CLASS%" "%SELECTOR%" %ENTRY_REST%
exit /b %errorlevel%

:version
if exist "%PROVENANCE%" (
    for /f "tokens=2 delims=:" %%A in ('findstr /c:"\"release\"" "%PROVENANCE%"') do set "REL=%%~A"
    for /f "tokens=2 delims=:" %%A in ('findstr /c:"\"release_version\"" "%PROVENANCE%"') do set "RELVSN=%%~A"
    for /f "tokens=2 delims=:" %%A in ('findstr /c:"\"beamtalk_version\"" "%PROVENANCE%"') do set "BTVSN=%%~A"
    for /f "tokens=2 delims=:" %%A in ('findstr /c:"\"otp_release\"" "%PROVENANCE%"') do set "OTPREL=%%~A"
    for /f "tokens=2 delims=:" %%A in ('findstr /c:"\"platform\"" "%PROVENANCE%"') do set "PLAT=%%~A"
    echo %RELEASE_NAME% %RELEASE_VSN%
    echo   beamtalk  %BTVSN:"=%
    echo   otp       %OTPREL:"=%
    echo   platform  %PLAT:"=%
) else (
    echo %RELEASE_NAME% %RELEASE_VSN%
)
exit /b 0

:usage
echo usage: %~nx0 {foreground^|stop^|ping^|remote_console^|eval^|rpc^|version} [args...] 1>&2
exit /b 2
