#!/bin/sh
# Copyright 2026 James Casey
# SPDX-License-Identifier: Apache-2.0
#
# Generated by `beamtalk release` — ADR 0125 §1.6/§1.7 (BT-3573). Do not edit;
# it is overwritten on every `beamtalk release`.
#
# Verbs: foreground (default) | stop | ping | remote_console | eval | rpc | version
set -eu

RELEASE_NAME="__RELEASE_NAME__"
RELEASE_VSN="__RELEASE_VSN__"
ERTS_VSN="__ERTS_VERSION__"
INCLUDE_ERTS="__INCLUDE_ERTS__"

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd -P)
ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd -P)
CONFIG_DIR="$ROOT/releases/$RELEASE_VSN"
PROVENANCE="$CONFIG_DIR/beamtalk-provenance.json"

# Resolve the erl to run: bundled ERTS when present (the default), else the
# host `erl` on PATH (ADR 0125 §1.3/§3.2). Cross-compilation is not
# supported, so a bundled ERTS is always for this host/arch.
if [ "$INCLUDE_ERTS" = "true" ] && [ -x "$ROOT/erts-$ERTS_VSN/bin/erl" ]; then
    ERL="$ROOT/erts-$ERTS_VSN/bin/erl"
    USING_HOST_ERTS=false
else
    ERL=$(command -v erl 2>/dev/null || true)
    if [ -z "$ERL" ]; then
        echo "error: no Erlang/OTP found — no bundled ERTS in '$ROOT', and 'erl' is not on PATH" >&2
        exit 1
    fi
    USING_HOST_ERTS=true
fi

# ADR 0125 §3.2 — under a host ERTS, refuse to boot outside the OTP major
# window this artifact's BEAM files are guaranteed to load on
# (host_major in [build_major, build_major + 2]). Not applicable when the
# release bundles its own ERTS: the artifact is exact.
check_otp_window() {
    [ "$USING_HOST_ERTS" = "true" ] || return 0
    [ -f "$PROVENANCE" ] || return 0
    req_min=$(grep -o '"min"[[:space:]]*:[[:space:]]*[0-9]*' "$PROVENANCE" | head -n1 | grep -o '[0-9]*$' || true)
    req_max=$(grep -o '"max"[[:space:]]*:[[:space:]]*[0-9]*' "$PROVENANCE" | head -n1 | grep -o '[0-9]*$' || true)
    built_otp_release=$(grep -o '"otp_release"[[:space:]]*:[[:space:]]*"[^"]*"' "$PROVENANCE" | head -n1 | sed -E 's/.*"([^"]*)"$/\1/')
    built_major=${built_otp_release%%-*}
    host_major=$("$ERL" -noshell -eval 'io:format("~s", [erlang:system_info(otp_release)]), halt().' 2>/dev/null | grep -o '^[0-9]*' || true)
    if [ -z "$host_major" ] || [ -z "$req_min" ] || [ -z "$req_max" ]; then
        return 0
    fi
    if [ "$host_major" -lt "$req_min" ] || [ "$host_major" -gt "$req_max" ]; then
        echo "$RELEASE_NAME $RELEASE_VSN cannot start on Erlang/OTP $host_major." >&2
        echo "" >&2
        echo "  This release's BEAM files were produced by OTP $built_major and will not load on" >&2
        echo "  an older VM." >&2
        echo "" >&2
        echo "  Required: Erlang/OTP $req_min-$req_max (built on $built_major)" >&2
        echo "  Found:    Erlang/OTP $host_major ($ERL)" >&2
        echo "" >&2
        echo "  Either install a supported Erlang/OTP version, or rebuild the release on this host." >&2
        exit 1
    fi
}

# `-boot` for every verb below *except* `foreground` — none of them may boot
# the full release (that would start the project's own application a second
# time). With no `-boot` flag, `erl` falls back to `$ROOTDIR/bin/start.boot`;
# with the bundled ERTS, this binary's own root-directory autodetection
# resolves `$ROOTDIR` to `$ROOT` (the release dir), which has no such file.
# `copy_erts` (BT-3571/BT-3573) copies a plain kernel+stdlib
# `start_clean.boot` alongside the bundled ERTS for exactly this — point at
# it explicitly when it is present; a host ERTS already has its own
# `$ROOTDIR/bin/start.boot` (a real OTP install always ships one), so no
# flag is needed there.
minimal_boot_args() {
    if [ "$INCLUDE_ERTS" = "true" ] && [ -f "$ROOT/erts-$ERTS_VSN/bin/start_clean.boot" ]; then
        printf -- '-boot %s' "$ROOT/erts-$ERTS_VSN/bin/start_clean"
    fi
}

# Every `lib/*/ebin` directory, as `-pa` flags — needed by `eval` (loads the
# runtime closure into a fresh VM with no boot script) and by the
# distribution clients (`stop`/`ping`/`rpc`), which reference
# `beamtalk_release_launcher` and `beamtalk_error` by name.
lib_pa_args() {
    for d in "$ROOT"/lib/*/ebin; do
        [ -d "$d" ] && printf ' -pa %s' "$d"
    done
}

# A short, collision-resistant node name for the throwaway client nodes
# (`stop`/`ping`/`rpc`) — `-hidden` and loopback-bound, so it never appears
# in the foreground node's regular node list.
client_sname() {
    printf '%s_%s_%s' "$RELEASE_NAME" "$1" "$$"
}

cookie_args() {
    if [ -n "${RELEASE_COOKIE:-}" ]; then
        printf -- '-setcookie %s' "$RELEASE_COOKIE"
    fi
}

usage() {
    echo "usage: $0 {foreground|stop|ping|remote_console|eval|rpc|version} [args...]" >&2
    exit 2
}

VERB="${1:-foreground}"
if [ $# -gt 0 ]; then
    shift
fi

case "$VERB" in
    foreground)
        check_otp_window
        # `-noshell -noinput`: a service has no interactive tty attached
        # (ADR 0125 §1.7 — "Stdout is the container's stdout", not an Erlang
        # shell prompt). Without these, `erl` attaches an interactive shell
        # that reads stdin; under a process supervisor (systemd, Docker,
        # `nohup`) stdin is typically closed or not a tty, so the shell sees
        # immediate EOF and the whole node terminates seconds after boot —
        # `Console` output (ADR 0099) is unaffected: it still goes to
        # stdout/stderr normally, this only turns off the interactive
        # `1> ` prompt reading from stdin.
        # shellcheck disable=SC2086
        exec "$ERL" -noshell -noinput -boot "$CONFIG_DIR/start" -boot_var RELEASE_DIR "$ROOT" \
            -config "$CONFIG_DIR/sys" -args_file "$CONFIG_DIR/vm.args"
        ;;
    stop)
        check_otp_window
        SNAME=$(client_sname stop)
        NODE="$RELEASE_NAME@$(uname -n | cut -d. -f1)"
        # shellcheck disable=SC2046,SC2086
        exec "$ERL" -noshell -hidden -sname "$SNAME" $(cookie_args) $(minimal_boot_args) $(lib_pa_args) \
            -eval "beamtalk_release_launcher:stop_client_main()." \
            -extra "$NODE"
        ;;
    ping)
        check_otp_window
        SNAME=$(client_sname ping)
        NODE="$RELEASE_NAME@$(uname -n | cut -d. -f1)"
        # shellcheck disable=SC2046,SC2086
        exec "$ERL" -noshell -hidden -sname "$SNAME" $(cookie_args) $(minimal_boot_args) $(lib_pa_args) \
            -eval "beamtalk_release_launcher:ping_client_main()." \
            -extra "$NODE"
        ;;
    remote_console)
        check_otp_window
        SNAME=$(client_sname rc)
        NODE="$RELEASE_NAME@$(uname -n | cut -d. -f1)"
        # ADR 0091: same-host attach only — plain loopback distribution, no
        # further authentication beyond the cookie handshake (ADR 0058).
        # shellcheck disable=SC2046,SC2086
        exec "$ERL" -hidden -sname "$SNAME" $(cookie_args) $(minimal_boot_args) -remsh "$NODE"
        ;;
    eval)
        check_otp_window
        [ $# -ge 1 ] || usage
        ARG="$1"
        set -f
        # shellcheck disable=SC2086
        set -- $ARG
        set +f
        [ $# -ge 2 ] || {
            echo "eval requires \"ClassName selector [args...]\"" >&2
            exit 2
        }
        CLASS="$1"
        SELECTOR="$2"
        shift 2
        # shellcheck disable=SC2046,SC2086
        exec "$ERL" -noshell $(minimal_boot_args) $(lib_pa_args) \
            -config "$CONFIG_DIR/sys" \
            -beamtalk_workspace console false \
            -eval "beamtalk_release_launcher:eval_main()." \
            -extra "$CLASS" "$SELECTOR" "$@"
        ;;
    rpc)
        check_otp_window
        [ $# -ge 1 ] || usage
        ARG="$1"
        set -f
        # shellcheck disable=SC2086
        set -- $ARG
        set +f
        [ $# -ge 2 ] || {
            echo "rpc requires \"ClassName selector [args...]\"" >&2
            exit 2
        }
        CLASS="$1"
        SELECTOR="$2"
        shift 2
        SNAME=$(client_sname rpc)
        NODE="$RELEASE_NAME@$(uname -n | cut -d. -f1)"
        # shellcheck disable=SC2046,SC2086
        exec "$ERL" -noshell -hidden -sname "$SNAME" $(cookie_args) $(minimal_boot_args) $(lib_pa_args) \
            -eval "beamtalk_release_launcher:rpc_client_main()." \
            -extra "$NODE" "$CLASS" "$SELECTOR" "$@"
        ;;
    version)
        if [ -f "$PROVENANCE" ]; then
            release=$(grep -o '"release"[[:space:]]*:[[:space:]]*"[^"]*"' "$PROVENANCE" | head -n1 | sed -E 's/.*"([^"]*)"$/\1/')
            release_version=$(grep -o '"release_version"[[:space:]]*:[[:space:]]*"[^"]*"' "$PROVENANCE" | head -n1 | sed -E 's/.*"([^"]*)"$/\1/')
            beamtalk_version=$(grep -o '"beamtalk_version"[[:space:]]*:[[:space:]]*"[^"]*"' "$PROVENANCE" | head -n1 | sed -E 's/.*"([^"]*)"$/\1/')
            otp_release=$(grep -o '"otp_release"[[:space:]]*:[[:space:]]*"[^"]*"' "$PROVENANCE" | head -n1 | sed -E 's/.*"([^"]*)"$/\1/')
            platform=$(grep -o '"platform"[[:space:]]*:[[:space:]]*"[^"]*"' "$PROVENANCE" | head -n1 | sed -E 's/.*"([^"]*)"$/\1/')
            echo "$release $release_version"
            echo "  beamtalk  $beamtalk_version"
            echo "  otp       $otp_release"
            echo "  platform  $platform"
        else
            echo "$RELEASE_NAME $RELEASE_VSN"
        fi
        ;;
    *)
        usage
        ;;
esac
