%% Copyright 2026 James Casey
%% SPDX-License-Identifier: Apache-2.0

%%% @doc Application callback module for the Beamtalk runtime.
-module(beamtalk_runtime_app).
-behaviour(application).

-export([start/2, stop/1]).

%% @private
-spec start(application:start_type(), term()) -> {ok, pid()} | {error, term()}.
start(_StartType, _StartArgs) ->
    %% Initialize extension registry ETS tables
    beamtalk_extensions:init(),
    
    %% Start the runtime supervisor tree (which starts beamtalk_bootstrap and pg)
    case beamtalk_runtime_sup:start_link() of
        {ok, _Pid} = Ok ->
            %% Try to load standard library modules to trigger auto-registration.
            %% The beamtalk module is generated by the compiler (not compiled from source),
            %% so it may not exist yet. If it does exist, it has an -on_load attribute
            %% that calls register_class/0, which creates a class process and registers
            %% it with the beamtalk_class registry.
            %%
            %% This must happen after pg is started (which happens in beamtalk_bootstrap
            %% via the supervisor tree).
            case code:ensure_loaded(beamtalk) of
                {module, beamtalk} ->
                    logger:info("Loaded Beamtalk stdlib module"),
                    Ok;
                {error, Reason} ->
                    %% Not an error - beamtalk module is generated by compiler
                    %% and may not exist in development builds
                    logger:debug("Beamtalk stdlib module not available: ~p", [Reason]),
                    Ok
            end;
        Error ->
            Error
    end.

%% @private
-spec stop(term()) -> ok.
stop(_State) ->
    ok.
