# Copyright 2026 James Casey
# SPDX-License-Identifier: Apache-2.0

<#
.SYNOPSIS
    Beamtalk-specific worktree setup hook.

.DESCRIPTION
    Called by worktree-up.ps1 to create per-worktree configuration.
    Generates .env file with unique port/node/socket for Erlang REPL isolation.

.PARAMETER WorktreePath
    Path to the worktree directory

.PARAMETER Branch
    Branch name (used for deriving port numbers)

.PARAMETER MainRepo
    Path to the main repository
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$WorktreePath,
    
    [Parameter(Mandatory=$true)]
    [string]$Branch,
    
    [Parameter(Mandatory=$false)]
    [string]$MainRepo
)

# Create .env file for devcontainer with node name and daemon socket derived from branch
# Port is no longer assigned per-worktree — the OS assigns ephemeral ports automatically (BT-192)
Write-Host "   Creating .env file for Beamtalk..." -ForegroundColor Gray
$envPath = Join-Path $WorktreePath ".env"

# Derive node name and daemon socket from branch name
$nodeName = "beamtalk@localhost"
# Use container path (remoteUser: vscode), not Windows host path
$daemonSocket = "/home/vscode/.beamtalk/daemon.sock"

if ($Branch -match "^BT-(\d+)") {
    $issueNum = [int]$matches[1]
    $nodeName = "beamtalk_bt${issueNum}@localhost"
    $daemonSocket = "/home/vscode/.beamtalk/daemon-bt${issueNum}.sock"
    Write-Host "   Node: $nodeName" -ForegroundColor Gray
}
elseif ($Branch -eq "main") {
    Write-Host "   Node: $nodeName (main default)" -ForegroundColor Gray
}
else {
    # Hash branch name for unique node name and daemon socket
    $hash = [System.Text.Encoding]::UTF8.GetBytes($Branch) | ForEach-Object { $_ } | Measure-Object -Sum
    $sanitizedBranch = $Branch -replace '[^a-zA-Z0-9]', '_'
    # Truncate sanitized branch name to prevent Unix socket path length issues (~108 bytes)
    if ($sanitizedBranch.Length -gt 20) {
        $hashMod = [int]($hash.Sum % 10000)
        $branchHash = "{0:D4}" -f $hashMod
        $sanitizedBranch = $sanitizedBranch.Substring(0, 20) + "_" + $branchHash
    }
    $nodeName = "beamtalk_${sanitizedBranch}@localhost"
    $daemonSocket = "/home/vscode/.beamtalk/daemon-${sanitizedBranch}.sock"
    Write-Host "   Node: $nodeName" -ForegroundColor Gray
}

# Write .env file
# Note: BEAMTALK_REPL_PORT is no longer set — the OS assigns an ephemeral port (BT-192)
@"
# Auto-generated by worktree-up-hook.ps1
# Configuration for Beamtalk REPL and compiler daemon in this worktree
BEAMTALK_NODE_NAME=$nodeName
BEAMTALK_DAEMON_SOCKET=$daemonSocket
"@ | Out-File -FilePath $envPath -Encoding utf8 -Force

Write-Host "   ✅ Created .env file" -ForegroundColor Green
