# Copyright 2026 James Casey
# SPDX-License-Identifier: Apache-2.0

<#
.SYNOPSIS
    Beamtalk-specific worktree setup hook.

.DESCRIPTION
    Called by worktree-up.ps1 to create per-worktree configuration.
    Generates .env file with unique port/node/socket for Erlang REPL isolation.

.PARAMETER WorktreePath
    Path to the worktree directory

.PARAMETER Branch
    Branch name (used for deriving port numbers)

.PARAMETER MainRepo
    Path to the main repository
#>

param(
    [Parameter(Mandatory=$true)]
    [string]$WorktreePath,
    
    [Parameter(Mandatory=$true)]
    [string]$Branch,
    
    [Parameter(Mandatory=$false)]
    [string]$MainRepo
)

# Create .env file for devcontainer with port and node name derived from branch
Write-Host "   Creating .env file for Beamtalk..." -ForegroundColor Gray
$envPath = Join-Path $WorktreePath ".env"

# Derive port from branch name
# BT-190 -> 49342, BT-64 -> 49216, main -> 49152
# Uses ephemeral port range (49152-65535) to avoid conflicts with common services
# Port ranges: BT branches 49152-50151 (capped at issue 999), hash-based 50152-51051
$port = 49152
$nodeName = "beamtalk@localhost"
# Use container path (remoteUser: vscode), not Windows host path
$daemonSocket = "/home/vscode/.beamtalk/daemon.sock"

if ($Branch -match "^BT-(\d+)") {
    $issueNum = [int]$matches[1]
    # Cap issue number to keep port in valid range (max 65535, but we cap at 999 for simplicity)
    if ($issueNum -gt 999) {
        Write-Host "   ⚠️ Issue number $issueNum too large, capping to 999" -ForegroundColor Yellow
        $issueNum = 999
    }
    $port = 49152 + $issueNum
    $nodeName = "beamtalk_bt${issueNum}@localhost"
    $daemonSocket = "/home/vscode/.beamtalk/daemon-bt${issueNum}.sock"
    Write-Host "   Port: $port (from $Branch)" -ForegroundColor Gray
    Write-Host "   Node: $nodeName" -ForegroundColor Gray
}
elseif ($Branch -eq "main") {
    Write-Host "   Port: $port (main default)" -ForegroundColor Gray
    Write-Host "   Node: $nodeName (main default)" -ForegroundColor Gray
}
else {
    # Hash branch name to port range 50152-51051 (non-overlapping with BT branches)
    $hash = [System.Text.Encoding]::UTF8.GetBytes($Branch) | ForEach-Object { $_ } | Measure-Object -Sum
    $port = 50152 + ($hash.Sum % 900)
    $sanitizedBranch = $Branch -replace '[^a-zA-Z0-9]', '_'
    # Truncate sanitized branch name to prevent Unix socket path length issues (~108 bytes)
    if ($sanitizedBranch.Length -gt 20) {
        $hashMod = [int]($hash.Sum % 10000)
        $branchHash = "{0:D4}" -f $hashMod
        $sanitizedBranch = $sanitizedBranch.Substring(0, 20) + "_" + $branchHash
    }
    $nodeName = "beamtalk_${sanitizedBranch}@localhost"
    $daemonSocket = "/home/vscode/.beamtalk/daemon-${sanitizedBranch}.sock"
    Write-Host "   Port: $port (from hash)" -ForegroundColor Gray
    Write-Host "   Node: $nodeName" -ForegroundColor Gray
}

# Write .env file
@"
# Auto-generated by worktree-up-hook.ps1
# Configuration for Beamtalk REPL and compiler daemon in this worktree
BEAMTALK_REPL_PORT=$port
BEAMTALK_NODE_NAME=$nodeName
BEAMTALK_DAEMON_SOCKET=$daemonSocket
"@ | Out-File -FilePath $envPath -Encoding utf8 -Force

Write-Host "   ✅ Created .env file" -ForegroundColor Green
