// Copyright 2026 James Casey
// SPDX-License-Identifier: Apache-2.0

//! The class-variable process-dictionary key shape (ADR 0130 §1, §2).
//!
//! **DDD Context:** Compilation — Code Generation
//!
//! Single Rust-side owner of the key shape that `beamtalk_class_vars` (Erlang
//! runtime) and the inlined class-variable reads and writes codegen emits
//! (Phase 0 gate 3: helper calls 2.3x, inlined 0.63x of today's cost) must
//! agree on. The shape crosses the Rust/Erlang boundary, so it is not copied:
//! this module is the source, [`erlang_header`] renders it into the checked-in
//! `runtime/apps/beamtalk_runtime/include/beamtalk_class_vars_keys.hrl`
//! (regenerated by `beamtalk build-stdlib`, guarded by
//! `just check-generated-builtins`), and `beamtalk_class_vars.erl` includes that
//! header instead of spelling the atoms.
//!
//! # Shape
//!
//! - class key: `{'$bt_class_vars', ClassTag}`, where `ClassTag` is the
//!   receiver's metaclass tag (`'Name class'`, `element(2, ClassSelf)`). The
//!   tag, not the bare class name, so an access recovers its key from `ClassSelf`
//!   with one `element/2` instead of a tag-to-name derivation on every read.
//! - home key: `'$bt_class_vars_home'`, naming the key of the live invocation.
//! - read-only marker: `{'$bt_class_vars_ro', ClassTag}`, planted under the
//!   class key by the runtime-owned out-of-process regions.

use beamtalk_cerl_doc::{Document, docvec, leaf};

/// First element of the class key tuple.
pub(super) const KEY_TAG: &str = "$bt_class_vars";
/// Process-dictionary key of the live-invocation entry.
pub(super) const HOME_KEY: &str = "$bt_class_vars_home";
/// First element of the read-only marker tuple.
pub(super) const RO_TAG: &str = "$bt_class_vars_ro";

/// The class-variable calling-convention version a compiled module declares in
/// `__beamtalk_meta/0` as `class_var_abi` (ADR 0130 §3): `1` is "class methods
/// are `class_<sel>(ClassSelf, Args...)` and class variables live in the
/// class process's dictionary". The runtime's load gate
/// (`beamtalk_class_vars:check_class_info_abi/2`, enforced at class registration,
/// hot reload and the release preflight) compares a module's `class_var_abi`
/// with `?BT_CLASS_VAR_ABI` in the generated header: this constant is the one
/// place the value is written.
pub(super) const ABI_VERSION: i64 = 1;

/// The class key for the class object `class_self_var` names:
/// `{'$bt_class_vars', call 'erlang':'element'(2, ClassSelf)}`.
pub(super) fn key_doc(class_self_var: &str) -> Document<'static> {
    docvec![
        "{",
        leaf::atom(KEY_TAG),
        ", call 'erlang':'element'(2, ",
        leaf::var(class_self_var),
        ")}"
    ]
}

/// Where the generator is in binding the class key once per method (BT-3719).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub(super) enum KeyScope {
    /// Not lowering a class-method body: an access inlines the key tuple.
    #[default]
    Unscoped,
    /// Inside a class-method body; no access has needed the key yet.
    Open,
    /// Inside a class-method body; the key is bound to this variable.
    Bound(String),
}

/// `let <key_var> = <class key> in `: binds the class key once so every
/// inlined access in a method body reuses it (BT-3719).
pub(super) fn key_binding_doc(key_var: &str, class_self_var: &str) -> Document<'static> {
    docvec![
        "let ",
        leaf::var(key_var),
        " = ",
        key_doc(class_self_var),
        " in "
    ]
}

/// Content of `beamtalk_class_vars_keys.hrl`, generated from the constants
/// above so the Erlang runtime and codegen share one key shape.
#[must_use]
pub fn erlang_header() -> String {
    format!(
        "%% AUTO-GENERATED by `beamtalk build-stdlib` from \
         crates/beamtalk-codegen/src/core_erlang/class_var_keys.rs — do not edit manually.\n\
         %% Copyright 2026 James Casey\n\
         %% SPDX-License-Identifier: Apache-2.0\n\
         \n\
         %% The class-variable process-dictionary key shape (ADR 0130 §1, §2), shared\n\
         %% with the inlined class-variable reads and writes codegen emits.\n\
         %% Regenerate with `just build-stdlib`; `just check-generated-builtins` fails\n\
         %% when this file is stale.\n\
         \n\
         -ifndef(BEAMTALK_CLASS_VARS_KEYS_HRL).\n\
         -define(BEAMTALK_CLASS_VARS_KEYS_HRL, true).\n\
         \n\
         %% The key of a class's variables; `ClassTag` is the metaclass tag\n\
         %% (`'Name class'`, `element(2, ClassSelf)`).\n\
         -define(BT_CLASS_VARS_KEY(ClassTag), {{'{KEY_TAG}', ClassTag}}).\n\
         \n\
         %% The process-dictionary key naming the live invocation's class key.\n\
         -define(BT_CLASS_VARS_HOME, '{HOME_KEY}').\n\
         \n\
         %% The read-only marker planted under a class key by `with_snapshot/2`.\n\
         -define(BT_CLASS_VARS_RO(ClassTag), {{'{RO_TAG}', ClassTag}}).\n\
         \n\
         %% The `class_var_abi` value compiled modules declare in `__beamtalk_meta/0`.\n\
         -define(BT_CLASS_VAR_ABI, {ABI_VERSION}).\n\
         \n\
         -endif.\n"
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn key_doc_renders_the_tag_keyed_tuple() {
        assert_eq!(
            key_doc("ClassSelf").to_pretty_string(),
            "{'$bt_class_vars', call 'erlang':'element'(2, ClassSelf)}"
        );
    }

    #[test]
    fn key_binding_doc_binds_the_key_once() {
        assert_eq!(
            key_binding_doc("_CVKey1", "ClassSelf").to_pretty_string(),
            "let _CVKey1 = {'$bt_class_vars', call 'erlang':'element'(2, ClassSelf)} in "
        );
    }

    /// The checked-in header is exactly what `build-stdlib` regenerates, so the
    /// Erlang runtime cannot drift from the shape codegen inlines.
    #[test]
    fn checked_in_header_matches_the_generator() {
        assert_eq!(
            include_str!(
                "../../../../runtime/apps/beamtalk_runtime/include/beamtalk_class_vars_keys.hrl"
            ),
            erlang_header()
        );
    }

    #[test]
    fn header_defines_the_shared_shape() {
        let hrl = erlang_header();
        assert!(
            hrl.contains("-define(BT_CLASS_VARS_KEY(ClassTag), {'$bt_class_vars', ClassTag}).")
        );
        assert!(hrl.contains("-define(BT_CLASS_VARS_HOME, '$bt_class_vars_home')."));
        assert!(
            hrl.contains("-define(BT_CLASS_VARS_RO(ClassTag), {'$bt_class_vars_ro', ClassTag}).")
        );
        assert!(hrl.contains("-define(BT_CLASS_VAR_ABI, 1)."));
    }
}
