// Copyright 2026 James Casey
// SPDX-License-Identifier: Apache-2.0

//! Non-local-return (NLR) try/catch scaffolding shared by the Actor,
//! class-method, and value-type calling conventions.
//!
//! **DDD Context:** Compilation — Code Generation
//!
//! The NLR value objects ([`NlrCatchVars`], [`NlrBoundary`],
//! [`NlrValueTypeCatchVars`]) and the `wrap_*_with_nlr_catch` family of
//! [`CoreErlangGenerator`] methods that build the try/catch scaffolding
//! around a 4-tuple `{'$bt_nlr', Token, Value, State}` throw. See ADR 0041.

use crate::core_erlang::generator::CoreErlangGenerator;
use beamtalk_cerl_doc::docvec;
use beamtalk_cerl_doc::leaf;
use beamtalk_cerl_doc::{Document, INDENT, line, nest};

/// Fresh temporary variable names shared by all three NLR try/catch wrappers.
///
/// Allocated by [`CoreErlangGenerator::alloc_nlr_catch_vars`] and consumed by the
/// single boundary-parameterised wrapper [`CoreErlangGenerator::wrap_body_with_nlr_catch`]
/// and by [`CoreErlangGenerator::wrap_value_type_body_with_nlr_catch`].
#[allow(clippy::struct_field_names)]
struct NlrCatchVars {
    result_var: String,
    cls_var: String,
    err_var: String,
    stk_var: String,
    ctk_var: String,
    val_var: String,
    /// State variable captured from the 4-tuple NLR throw.
    state_var: String,
    ot_pair_var: String,
}

/// The per-context NLR boundary — the *only* thing that differs between the
/// Actor, class-method and value-type non-local-return catch wrappers once the catch
/// vars are shared.
///
/// All three contexts catch the same 4-tuple throw `{'$bt_nlr', Token, Value, State}`
/// (ADR 0041's state-carrying NLR convention); they disagree only about the Document
/// the matching catch arm yields. This enum captures that single axis so the catch
/// scaffolding can be written once (see [`nlr_arm_result`]) instead of being
/// copy-evolved per context.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(in crate::core_erlang) enum NlrBoundary {
    /// Actor (`gen_server`) methods: the catch arm yields `{'reply', Value, State}`.
    ActorReply,
    /// Class methods: the catch arm yields `Value` (no class vars) or
    /// `{'class_var_result', Value, State}` when class vars were mutated.
    ClassMethod { has_class_vars: bool },
    /// Value-type methods: the catch arm yields `{Value, State}` so the normal and
    /// NLR-catch paths produce the same `{Result, Self{N}}` shape.
    ValueType,
}

/// Builds the Document the matching NLR catch arm yields for `boundary`.
///
/// This is the single place the per-context divergence between the three former
/// `wrap_*_body_with_nlr_catch` wrappers lives. `val_var`/`state_var` are the
/// catch-bound `Value`/`State` extracted from the 4-tuple throw. Shared by the
/// gen-server wrapper ([`CoreErlangGenerator::wrap_body_with_nlr_catch`]) and the
/// value-type suffix ([`NlrValueTypeCatchVars::format_catch_suffix`]).
///
/// Use Document/docvec! — never format!() for Core Erlang fragments.
fn nlr_arm_result(val_var: &str, state_var: &str, boundary: NlrBoundary) -> Document<'static> {
    match boundary {
        NlrBoundary::ActorReply => docvec![
            "{'reply', ",
            leaf::var(val_var.to_string()),
            ", ",
            leaf::var(state_var.to_string()),
            "}",
        ],
        NlrBoundary::ClassMethod {
            has_class_vars: true,
        } => docvec![
            "{'class_var_result', ",
            leaf::var(val_var.to_string()),
            ", ",
            leaf::var(state_var.to_string()),
            "}",
        ],
        NlrBoundary::ClassMethod {
            has_class_vars: false,
        } => leaf::var(val_var.to_string()),
        NlrBoundary::ValueType => docvec![
            "{",
            leaf::var(val_var.to_string()),
            ", ",
            leaf::var(state_var.to_string()),
            "}",
        ],
    }
}

/// Variable names for value type NLR try/catch wrapping.
///
/// Holds the fresh temporary variable names generated by
/// `wrap_value_type_body_with_nlr_catch` so the caller can emit the
/// try/catch template with consistent variable names.
#[allow(clippy::struct_field_names)]
pub(in crate::core_erlang) struct NlrValueTypeCatchVars {
    pub token_var: String,
    pub result_var: String,
    pub cls_var: String,
    pub err_var: String,
    pub stk_var: String,
    pub ctk_var: String,
    pub val_var: String,
    /// State variable captured from the 4-tuple NLR throw.
    pub state_var: String,
    pub ot_pair_var: String,
}

impl NlrValueTypeCatchVars {
    /// Formats the try prefix for the NLR wrapper.
    ///
    /// Returns `Document` instead of `String` for composable codegen.
    ///
    /// ```text
    /// let TokenVar = call 'erlang':'make_ref'() in
    /// try
    /// ```
    pub fn format_try_prefix(&self) -> Document<'static> {
        docvec![
            "    let ",
            leaf::var(self.token_var.clone()),
            " = call 'erlang':'make_ref'() in",
            nest(INDENT, line()),
            "try",
            line(),
        ]
    }

    /// Formats the catch suffix for the NLR wrapper.
    ///
    /// Returns `Document` instead of `String` for composable codegen.
    /// Catches 4-tuple NLR throws and returns `{NlrVal, NlrState}`.
    ///
    /// ```text
    /// of Result -> Result
    /// catch <Cls, Err, Stk> ->
    ///   case {Cls, Err} of
    ///     <{'throw', {'$bt_nlr', CatchTok, Val, State}}> when ... -> {Val, State}
    ///     <Other> when 'true' -> primop 'raw_raise'(Cls, Err, Stk)
    ///   end
    /// ```
    pub fn format_catch_suffix(&self) -> Document<'static> {
        docvec![
            nest(INDENT, line()),
            "of ",
            leaf::var(self.result_var.clone()),
            " -> ",
            leaf::var(self.result_var.clone()),
            nest(INDENT, line()),
            "catch <",
            leaf::var(self.cls_var.clone()),
            ", ",
            leaf::var(self.err_var.clone()),
            ", ",
            leaf::var(self.stk_var.clone()),
            "> ->",
            nest(INDENT + 2, line()),
            "case {",
            leaf::var(self.cls_var.clone()),
            ", ",
            leaf::var(self.err_var.clone()),
            "} of",
            nest(INDENT + 4, line()),
            "<{'throw', {'$bt_nlr', ",
            leaf::var(self.ctk_var.clone()),
            ", ",
            leaf::var(self.val_var.clone()),
            ", ",
            leaf::var(self.state_var.clone()),
            "}}> ",
            "when call 'erlang':'=:='(",
            leaf::var(self.ctk_var.clone()),
            ", ",
            leaf::var(self.token_var.clone()),
            ") -> ",
            // Shared catch-arm builder — value-type yields `{Value, State}`.
            nlr_arm_result(&self.val_var, &self.state_var, NlrBoundary::ValueType),
            nest(INDENT + 4, line()),
            "<",
            leaf::var(self.ot_pair_var.clone()),
            "> when 'true' -> ",
            "primop 'raw_raise'(",
            leaf::var(self.cls_var.clone()),
            ", ",
            leaf::var(self.err_var.clone()),
            ", ",
            leaf::var(self.stk_var.clone()),
            ")",
            nest(INDENT + 2, line()),
            "end",
            line(),
        ]
    }
}

impl CoreErlangGenerator {
    /// Allocates fresh temporary variable names for an NLR try/catch wrapper.
    fn alloc_nlr_catch_vars(&mut self) -> NlrCatchVars {
        NlrCatchVars {
            result_var: self.fresh_temp_var("NlrResult"),
            cls_var: self.fresh_temp_var("NlrCls"),
            err_var: self.fresh_temp_var("NlrErr"),
            stk_var: self.fresh_temp_var("NlrStk"),
            ctk_var: self.fresh_temp_var("CatchTok"),
            val_var: self.fresh_temp_var("NlrVal"),
            state_var: self.fresh_temp_var("NlrState"),
            ot_pair_var: self.fresh_temp_var("OtherPair"),
        }
    }

    /// The single boundary-parameterised NLR try/catch wrapper.
    ///
    /// Shares its try/catch scaffolding across the Actor and class-method
    /// boundaries (and its catch-arm builder with the value-type wrapper).
    /// The try/catch scaffolding — make the NLR token, `try`/`of`
    /// the body, `catch` the 4-tuple `{'$bt_nlr', Token, Value, State}` throw — is
    /// identical across contexts; only the matching arm's result Document varies, which
    /// `boundary` selects via [`nlr_arm_result`].
    ///
    /// Use Document/docvec! — never format!() for Core Erlang fragments.
    pub(in crate::core_erlang) fn wrap_body_with_nlr_catch(
        &mut self,
        body_doc: Document<'static>,
        token_var: &str,
        boundary: NlrBoundary,
    ) -> Document<'static> {
        // ADR 0111 Phase D: this is the true call site
        // `ThreadedStmt::NlrCatch` faithfully models (module docs on
        // `threaded_ir::ThreadedStmt::NlrCatch`) — every NLR try/catch this
        // generator ever emits (Actor/ClassMethod/ValueType alike) is built
        // here; its `boundary` shape is also what
        // `threaded_ir::construct_and_verify_class_var_bind`'s synthetic
        // marker (built from its `frame`/`shadow_write_eligible` pair, ADR
        // 0111 Addendum 9) reconstructs at the class-var
        // Bind-emission sites (`expressions.rs`, `dispatch_codegen.rs`) for
        // the ADR 0110 ShadowWriteMissing contract. No standalone
        // `verify()` call here: a
        // lone `NlrCatch` with no `Bind` can never trigger any
        // `VerifyError` (`walk_stmt` treats it as a no-op), so constructing
        // one on every NLR-catch wrap — a hot path — would pay a real
        // allocation for a check that can't fire (caught in review).

        let vars = self.alloc_nlr_catch_vars();
        let nlr_arm_result = nlr_arm_result(&vars.val_var, &vars.state_var, boundary);
        let NlrCatchVars {
            result_var,
            cls_var,
            err_var,
            stk_var,
            ctk_var,
            val_var,
            state_var,
            ot_pair_var,
        } = vars;

        docvec![
            "let ",
            leaf::var(token_var.to_string()),
            " = call 'erlang':'make_ref'() in\n",
            "try\n",
            body_doc,
            "\n",
            "of ",
            leaf::var(result_var.clone()),
            " -> ",
            leaf::var(result_var),
            "\n",
            "catch <",
            leaf::var(cls_var.clone()),
            ", ",
            leaf::var(err_var.clone()),
            ", ",
            leaf::var(stk_var.clone()),
            "> ->\n",
            "  case {",
            leaf::var(cls_var.clone()),
            ", ",
            leaf::var(err_var.clone()),
            "} of\n",
            "    <{'throw', {'$bt_nlr', ",
            leaf::var(ctk_var.clone()),
            ", ",
            leaf::var(val_var),
            ", ",
            leaf::var(state_var),
            "}}> ",
            "when call 'erlang':'=:='(",
            leaf::var(ctk_var),
            ", ",
            leaf::var(token_var.to_string()),
            ") -> ",
            nlr_arm_result,
            "\n",
            "    <",
            leaf::var(ot_pair_var),
            "> when 'true' -> ",
            "primop 'raw_raise'(",
            leaf::var(cls_var),
            ", ",
            leaf::var(err_var),
            ", ",
            leaf::var(stk_var),
            ")\n",
            "  end",
        ]
    }

    /// Wraps a value type method body with NLR (non-local return) try/catch.
    ///
    /// Value type NLR uses a 4-element throw tuple `{$bt_nlr, Token, Value, State}`
    /// and catches it to return `{Value, State}`. The body parts are provided as a
    /// `Document` and the result is a complete function definition document.
    pub(in crate::core_erlang) fn wrap_value_type_body_with_nlr_catch(
        &mut self,
        token_var: &str,
    ) -> NlrValueTypeCatchVars {
        let NlrCatchVars {
            result_var,
            cls_var,
            err_var,
            stk_var,
            ctk_var,
            val_var,
            state_var,
            ot_pair_var,
        } = self.alloc_nlr_catch_vars();

        NlrValueTypeCatchVars {
            token_var: token_var.to_string(),
            result_var,
            cls_var,
            err_var,
            stk_var,
            ctk_var,
            val_var,
            state_var,
            ot_pair_var,
        }
    }

    /// Returns the current NLR token variable name, if any.
    pub(in crate::core_erlang) fn current_nlr_token(&self) -> Option<&String> {
        self.value_type_context
            .as_ref()
            .and_then(|ctx| ctx.current_nlr_token.as_ref())
    }

    /// Sets the current NLR token variable name.
    pub(in crate::core_erlang) fn set_current_nlr_token(&mut self, token: Option<String>) {
        self.value_type_context_mut().current_nlr_token = token;
    }
}
