#!/usr/bin/env escript
%% Copyright 2026 James Casey
%% SPDX-License-Identifier: Apache-2.0

%% Validate Dialyzer -spec attributes generated by the Beamtalk compiler.
%%
%% Core Erlang compilation does not preserve -spec attributes in BEAM debug_info,
%% so Dialyzer cannot analyse compiled .bt output directly. This script validates
%% specs by:
%%
%%   1. Reading .core files and extracting 'spec' attribute terms
%%   2. Evaluating the spec terms as Erlang data structures
%%   3. Constructing abstract forms that include those specs + function stubs
%%   4. Compiling the abstract forms to BEAM with debug_info
%%   5. Running Dialyzer on the resulting BEAM files
%%
%% This preserves the ACTUAL type information from the generated specs (e.g.
%% integer(), binary(), any()) rather than replacing everything with any().
%%
%% Usage:
%%   escript scripts/validate_specs.escript <core-dir>
%%
%% The <core-dir> should contain .core files produced by `beamtalk build`.
%%
%% Exit codes:
%%   0 — all specs valid
%%   1 — validation errors found

main(Args) ->
    CoreDir = parse_args(Args),
    case filelib:is_dir(CoreDir) of
        false ->
            io:format(standard_error, "Error: directory not found: ~s~n", [CoreDir]),
            halt(1);
        true -> ok
    end,

    CoreFiles = filelib:wildcard(filename:join(CoreDir, "*.core")),
    case CoreFiles of
        [] ->
            io:format("No .core files found in ~s~n", [CoreDir]),
            halt(0);
        _ ->
            io:format("Found ~p .core files~n", [length(CoreFiles)])
    end,

    %% Create temp directory for BEAM output
    TmpDir = make_tmp_dir(),
    BeamDir = filename:join(TmpDir, "beams"),
    ok = filelib:ensure_dir(filename:join(BeamDir, "x")),

    %% Process each .core file: extract specs, build abstract forms, compile
    {TotalSpecs, ModulesWithSpecs, CompileErrors} =
        lists:foldl(
            fun(CoreFile, {Specs, Mods, Errs}) ->
                case process_core_file(CoreFile, BeamDir) of
                    {ok, N} when N > 0 -> {Specs + N, Mods + 1, Errs};
                    {ok, _} -> {Specs, Mods, Errs};
                    {error, Reason} ->
                        io:format(standard_error,
                                  "Error processing ~s: ~p~n",
                                  [filename:basename(CoreFile), Reason]),
                        {Specs, Mods, Errs + 1}
                end
            end,
            {0, 0, 0},
            CoreFiles),

    case CompileErrors > 0 of
        true ->
            io:format(standard_error,
                      "~p file(s) had errors during spec extraction/compilation.~n",
                      [CompileErrors]),
            cleanup(TmpDir),
            halt(1);
        false -> ok
    end,

    case TotalSpecs of
        0 ->
            io:format("No specs found — nothing to validate.~n"),
            cleanup(TmpDir),
            halt(0);
        _ ->
            io:format("Extracted ~p spec(s) from ~p module(s)~n",
                       [TotalSpecs, ModulesWithSpecs])
    end,

    %% Run Dialyzer on the generated BEAMs
    BeamFiles = filelib:wildcard(filename:join(BeamDir, "*.beam")),
    io:format("Running Dialyzer on ~p BEAM files...~n", [length(BeamFiles)]),

    case run_dialyzer(BeamFiles) of
        ok ->
            io:format("Dialyzer: no warnings — all ~p spec(s) are valid.~n",
                       [TotalSpecs]),
            cleanup(TmpDir),
            halt(0);
        {warnings, Warnings} ->
            io:format(standard_error,
                      "~nDialyzer found ~p warning(s):~n", [length(Warnings)]),
            lists:foreach(fun(W) ->
                io:format(standard_error, "  ~s~n", [dialyzer:format_warning(W)])
            end, Warnings),
            cleanup(TmpDir),
            halt(1);
        {error, Msg} ->
            io:format(standard_error, "~nDialyzer error: ~s~n", [Msg]),
            cleanup(TmpDir),
            halt(1)
    end.

%% ── Argument parsing ──────────────────────────────────────────────────────

parse_args([CoreDir]) ->
    CoreDir;
parse_args(_) ->
    io:format(standard_error,
              "Usage: validate_specs.escript <core-dir>~n", []),
    halt(1).

%% ── Core file processing ────────────────────────────────────────────────

%% Read a .core file, extract spec attributes, construct abstract forms,
%% and compile to BEAM with debug_info.
process_core_file(CoreFile, BeamDir) ->
    case file:read_file(CoreFile) of
        {ok, Bin} ->
            Content = binary_to_list(Bin),
            case extract_module_name(Content) of
                {ok, ModName} ->
                    case extract_spec_term(Content) of
                        {ok, SpecEntries} when length(SpecEntries) > 0 ->
                            Forms = build_abstract_forms(ModName, SpecEntries),
                            case compile:forms(Forms, [debug_info,
                                                       {outdir, BeamDir},
                                                       return_errors]) of
                                {ok, ModName, BeamBin} ->
                                    BeamFile = filename:join(BeamDir,
                                        atom_to_list(ModName) ++ ".beam"),
                                    ok = file:write_file(BeamFile, BeamBin),
                                    {ok, length(SpecEntries)};
                                {ok, ModName, BeamBin, _Warnings} ->
                                    BeamFile = filename:join(BeamDir,
                                        atom_to_list(ModName) ++ ".beam"),
                                    ok = file:write_file(BeamFile, BeamBin),
                                    {ok, length(SpecEntries)};
                                {error, Errors, _} ->
                                    {error, {compile, Errors}}
                            end;
                        {ok, []} ->
                            {ok, 0};
                        {error, Reason} ->
                            {error, {spec_parse, Reason}}
                    end;
                error ->
                    {error, no_module_name}
            end;
        {error, Reason} ->
            {error, {read_file, Reason}}
    end.

%% Extract module name from: module 'name' [...]
extract_module_name(Content) ->
    case re:run(Content, "^module\\s+'([^']+)'",
                [{capture, [1], list}, multiline]) of
        {match, [Name]} -> {ok, list_to_atom(Name)};
        nomatch -> error
    end.

%% Extract the spec term from the Core Erlang source.
%% The spec attribute looks like:
%%   'spec' = [{{'fun_name', Arity}, [TypeInfo]}]
%%
%% We extract the full Erlang term between 'spec' = and the closing ]].
extract_spec_term(Content) ->
    %% Core Erlang emits one 'spec' = [...] per annotated method.
    %% Each looks like:
    %%   'spec' =\n        [{{'fun_name', Arity}, [TypeInfo]}],
    %%
    %% We find ALL 'spec' = positions and extract the balanced [...] value
    %% using bracket counting (regex can't handle nested brackets).
    case re:run(Content, "'spec'\\s*=\\s*",
                [global, {capture, first, index}]) of
        {match, Matches} ->
            extract_all_specs(Content, Matches, []);
        nomatch ->
            {ok, []}
    end.

extract_all_specs(_Content, [], Acc) ->
    {ok, lists:reverse(Acc)};
extract_all_specs(Content, [[{Start, Len}] | Rest], Acc) ->
    %% Skip past 'spec' = to the opening [
    ValueStart = Start + Len,
    Tail = string:substr(Content, ValueStart + 1),
    %% Skip whitespace to find the opening [
    TailTrimmed = string:strip(Tail, left),
    case TailTrimmed of
        [$[ | _] ->
            case extract_balanced_brackets(TailTrimmed) of
                {ok, SpecStr} ->
                    case erl_scan:string(SpecStr ++ ".") of
                        {ok, Tokens, _} ->
                            case erl_parse:parse_term(Tokens) of
                                {ok, [Entry]} ->
                                    extract_all_specs(Content, Rest, [Entry | Acc]);
                                {ok, Entries} when is_list(Entries) ->
                                    extract_all_specs(Content, Rest,
                                                      lists:reverse(Entries) ++ Acc);
                                {error, Reason} ->
                                    {error, {parse_term, Reason, SpecStr}}
                            end;
                        {error, Reason, _} ->
                            {error, {scan, Reason, SpecStr}}
                    end;
                {error, Reason} ->
                    {error, {brackets, Reason}}
            end;
        _ ->
            %% No opening bracket found, skip
            extract_all_specs(Content, Rest, Acc)
    end.

%% Extract a balanced bracket expression starting from an opening [.
%% Returns the full string including the outer brackets.
extract_balanced_brackets(Str) ->
    extract_balanced(Str, 0, [], false).

extract_balanced([], _Depth, _Acc, _InAtom) ->
    {error, unbalanced};
extract_balanced([$' | Rest], Depth, Acc, false) ->
    %% Start of atom literal — skip until closing '
    extract_balanced(Rest, Depth, [$' | Acc], true);
extract_balanced([$' | Rest], Depth, Acc, true) ->
    %% End of atom literal
    extract_balanced(Rest, Depth, [$' | Acc], false);
extract_balanced([$[ | Rest], Depth, Acc, false) ->
    extract_balanced(Rest, Depth + 1, [$[ | Acc], false);
extract_balanced([$] | _Rest], 1, Acc, false) ->
    %% Closing the outermost bracket — done
    {ok, lists:reverse([$] | Acc])};
extract_balanced([$] | Rest], Depth, Acc, false) when Depth > 1 ->
    extract_balanced(Rest, Depth - 1, [$] | Acc], false);
extract_balanced([C | Rest], Depth, Acc, InAtom) ->
    extract_balanced(Rest, Depth, [C | Acc], InAtom).

%% ── Abstract form construction ──────────────────────────────────────────

%% Build a complete set of abstract forms for a module with specs.
%% The forms include:
%%   - module attribute
%%   - export attribute (all spec'd functions)
%%   - spec attributes (from extracted Core Erlang specs)
%%   - function stubs (each calls erlang:nif_error/1 to avoid return-type
%%     mismatches — Dialyzer infers no_return() which is the bottom type)
build_abstract_forms(ModName, SpecEntries) ->
    Line = erl_anno:new(1),

    %% Extract {FunName, Arity} pairs
    FunArities = [{FunName, Arity} || {{FunName, Arity}, _TypeInfo} <- SpecEntries],

    %% Module attribute
    ModAttr = {attribute, Line, module, ModName},

    %% Export attribute
    ExportAttr = {attribute, Line, export, FunArities},

    %% Spec attributes — use the actual type info from the Core Erlang
    SpecAttrs = lists:map(
        fun({{FunName, Arity}, TypeInfo}) ->
            {attribute, Line, spec, {{FunName, Arity}, TypeInfo}}
        end,
        SpecEntries),

    %% Function stubs — body is erlang:nif_error(undef) so Dialyzer
    %% infers no_return(), avoiding false spec/body mismatches.
    FunDecls = lists:map(
        fun({FunName, Arity}) ->
            Params = [{var, Line, list_to_atom("_A" ++ integer_to_list(I))}
                      || I <- lists:seq(1, Arity)],
            Body = [{call, Line,
                     {remote, Line,
                      {atom, Line, erlang},
                      {atom, Line, nif_error}},
                     [{atom, Line, undef}]}],
            {function, Line, FunName, Arity,
             [{clause, Line, Params, [], Body}]}
        end,
        FunArities),

    %% Eof
    Eof = {eof, Line},

    [ModAttr, ExportAttr] ++ SpecAttrs ++ FunDecls ++ [Eof].

%% ── Dialyzer ────────────────────────────────────────────────────────────

run_dialyzer(BeamFiles) ->
    try
        PltOpts = ensure_plt(),
        %% Use {warnings, []} to suppress return-type mismatch warnings
        %% from the nif_error stubs. Dialyzer still validates that all type
        %% expressions in specs are well-formed (unknown types cause a crash).
        case dialyzer:run([{files, BeamFiles},
                           {warnings, []},
                           {analysis_type, succ_typings}] ++ PltOpts) of
            [] -> ok;
            Warnings -> {warnings, Warnings}
        end
    catch
        throw:{dialyzer_error, Msg} ->
            {error, Msg}
    end.

%% Ensure a Dialyzer PLT exists.  If the default PLT is missing (e.g. in CI
%% where `rebar3 dialyzer` hasn't run), build a minimal one with just the
%% core OTP apps that generated specs reference.
ensure_plt() ->
    DefaultPlt = dialyzer_plt:get_default_plt(),
    case filelib:is_file(DefaultPlt) of
        true ->
            [];
        false ->
            io:format("Building minimal Dialyzer PLT (first run)...~n"),
            Apps = [erts, kernel, stdlib],
            Dirs = [code:lib_dir(A, ebin) || A <- Apps],
            ok = filelib:ensure_dir(DefaultPlt),
            dialyzer:run([{analysis_type, plt_build},
                          {output_plt, DefaultPlt},
                          {files_rec, Dirs}]),
            io:format("PLT built at ~s~n", [DefaultPlt]),
            []
    end.

%% ── Utilities ───────────────────────────────────────────────────────────

make_tmp_dir() ->
    TmpBase = case os:getenv("TMPDIR") of
        false ->
            case os:type() of
                {win32, _} -> os:getenv("TEMP", "C:\\Temp");
                _ -> "/tmp"
            end;
        Dir -> Dir
    end,
    TmpDir = filename:join(TmpBase,
        "bt_spec_validate_" ++ integer_to_list(erlang:unique_integer([positive]))),
    ok = filelib:ensure_dir(filename:join(TmpDir, "x")),
    TmpDir.

cleanup(TmpDir) ->
    lists:foreach(fun(F) -> file:delete(F) end,
                  filelib:wildcard(filename:join([TmpDir, "**", "*"]))),
    SubDirs = lists:reverse(lists:sort(
        filelib:wildcard(filename:join([TmpDir, "**"])))),
    lists:foreach(fun(D) ->
        case filelib:is_dir(D) of
            true -> file:del_dir(D);
            false -> ok
        end
    end, SubDirs),
    file:del_dir(TmpDir).
