// Copyright 2026 James Casey
// SPDX-License-Identifier: Apache-2.0

//! Page scaffolding: header and footer shared by the registry index and
//! detail pages.
//!
//! **DDD Context:** CLI / Documentation

/// Generate the HTML page header with the top navigation bar.
///
/// `title` is the `<title>` tag content. All registry pages live flat in one
/// output directory (there is no nesting to account for, unlike
/// `commands::doc`'s `apidocs/`/`docs/`/`adr/` split), so links are always
/// relative to that directory.
pub(super) fn page_header(title: &str) -> String {
    format!(
        "<!DOCTYPE html>\n\
         <html lang=\"en\">\n\
         <head>\n\
         <meta charset=\"utf-8\">\n\
         <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n\
         <title>{title}</title>\n\
         <link rel=\"stylesheet\" href=\"style.css\">\n\
         </head>\n\
         <body>\n\
         <header class=\"top-nav\">\n\
         <a class=\"nav-logo\" href=\"index.html\">Beamtalk Registry</a>\n\
         <nav class=\"nav-links\">\n\
         <a href=\"https://www.beamtalk.dev/\">Beamtalk</a>\n\
         <a href=\"https://github.com/jamesc/beamtalk-registry\" class=\"nav-github\">Registry source ↗</a>\n\
         </nav>\n\
         </header>\n\
         <main class=\"main-content\">\n",
    )
}

/// Generate the HTML page footer.
pub(super) fn page_footer() -> String {
    "</main>\n\
     <footer>\n\
     <p>Generated by <code>beamtalk registry site</code> — a read-only view \
     of the <a href=\"https://github.com/jamesc/beamtalk-registry\">registry \
     index</a>. See <a href=\"https://github.com/jamesc/beamtalk/blob/main/docs/beamtalk-packages.md#package-registry\">Package Registry</a> \
     in the Beamtalk docs.</p>\n\
     </footer>\n\
     </body>\n\
     </html>\n"
        .to_string()
}
