%% Copyright 2026 James Casey
%% SPDX-License-Identifier: Apache-2.0

-module(beamtalk_message_dispatch).

%%% **DDD Context:** Object System Context

-include("beamtalk.hrl").

-moduledoc """
Unified message dispatch entry point.

All non-intrinsic message sends are routed through this module,
replacing the inline type-checking code previously generated by
dispatch_codegen.rs (BT-223).

## Dispatch Strategy

### send/3 (sync — returns value)

| Receiver Type    | Dispatch Path | Returns |
|------------------|---------------|---------|
| Supervisor tuple | hierarchy walk via `beamtalk_dispatch:lookup/5` (ADR 0059) | Value |
| Actor record     | `beamtalk_actor:sync_send/3` | Value |
| Class object     | `beamtalk_object_class:class_send/3` | Value |
| Primitive        | `beamtalk_primitive:send/3` | Value |

### send/4 (sync with explicit timeout — returns value) (BT-1190)

Same as send/3 but passes Timeout to `beamtalk_actor:sync_send/4`.
For non-actor receivers, timeout is ignored and dispatch falls through
to the normal synchronous path.

### cast/3 (fire-and-forget — returns ok) (BT-920)

| Receiver Type    | Dispatch Path | Returns |
|------------------|---------------|---------|
| Supervisor tuple | (silently ignored — cast has no supervisor semantics) | ok |
| Actor record     | `beamtalk_actor:cast_send/3` | ok |
| Class object     | (silently ignored) | ok |
| Primitive        | (silently ignored) | ok |

### send_number_coercion/4 (sync — returns value) (BT-3262, ADR 0116)

Wraps send/3 for number-on-the-left arithmetic coercion (`5 + aVector`):
delegates to send/3, and on a `does_not_understand` for the exact
`Right`/`Selector` this call was for, re-raises it with a hint naming the
original operator before it reaches the caller. Any other exception
propagates unchanged.

## Usage (from generated Core Erlang)

```erlang
call 'beamtalk_message_dispatch':'send'(Receiver, 'selector', [Args])
call 'beamtalk_message_dispatch':'cast'(Receiver, 'selector', [Args])
call 'beamtalk_message_dispatch':'send_number_coercion'(
    Right, 'plusFromNumber:', [Left], '+')
```

See: ADR 0006 (Unified Method Dispatch), BT-430, ADR 0043 (BT-918)
""".
-export([send/3, send/4, cast/3, send_number_coercion/4]).

%% Compiled stdlib modules are generated from Core Erlang.
%% Dialyzer can't resolve them if stdlib hasn't been built yet.
% elp:fixme W0048 intentional suppression for dynamic dispatch
-dialyzer({nowarn_function, [send/3, send/4, cast/3]}).

-doc """
Send a message to any receiver (actor, class object, primitive, or future).

For futures, auto-awaits the value and re-dispatches (BT-840).
For supervisors, dispatches via hierarchy walk (ADR 0059 — not gen_server).
For actors, sends synchronously via gen_server:call (BT-918 / ADR 0043).
For class objects, dispatches synchronously via class_send.
For primitives, dispatches synchronously via beamtalk_primitive:send/3.
""".
-spec send(term(), atom(), list()) -> term().
send(Receiver, 'perform:withArguments:timeout:', [TargetSelector, ArgList, Timeout]) when
    is_atom(TargetSelector),
    is_list(ArgList),
    (is_integer(Timeout) andalso Timeout >= 0 orelse Timeout =:= infinity)
->
    %% BT-1190: Intercept perform:withArguments:timeout: at the dispatch level.
    %% Rewrites to send/4 so that the gen_server:call to the target uses the
    %% custom timeout, rather than sending perform:withArguments:timeout: as a
    %% regular message (which would use the default 5s timeout).
    send(Receiver, TargetSelector, ArgList, Timeout);
send({beamtalk_future, _} = Future, Selector, Args) ->
    %% BT-840: Auto-await futures in chained message sends.
    %% This enables backward compat during migration — any residual futures
    %% returned by old code paths are awaited before re-dispatching.
    Value = beamtalk_future:await(Future),
    send(Value, Selector, Args);
send({beamtalk_supervisor, ClassName, _Module, Pid} = _Self, isAlive, []) ->
    %% ADR 0059: Supervisor lifecycle — check process liveness without gen_server.
    is_process_alive(Pid) andalso ClassName =/= undefined;
send({beamtalk_supervisor, ClassName, _Module, Pid} = _Self, stop, []) ->
    %% ADR 0059: Supervisor stop — OTP supervisors are gen_servers; use gen_server:stop/1.
    %% Catch noproc so a stale handle raises a structured error rather than a raw OTP exit.
    try
        gen_server:stop(Pid),
        nil
    catch
        %% gen_server:stop/1 exits with bare noproc when the process is dead;
        %% the {noproc, _} tuple form guards the gen_server:call path defensively.
        exit:Reason when
            Reason =:= noproc orelse
                (tuple_size(Reason) =:= 2 andalso element(1, Reason) =:= noproc)
        ->
            Error = beamtalk_error:new(
                runtime_error,
                ClassName,
                stop,
                <<"supervisor is not running; the handle is stale">>
            ),
            beamtalk_exception_handler:reraise(Error)
    end;
send({beamtalk_supervisor, ClassName, _Module, _Pid} = Self, Selector, Args) ->
    %% ADR 0059: Route supervisor method calls via class hierarchy walk.
    %% Supervisor instances do not run in a gen_server — methods execute
    %% in the caller's process context (OTP supervisor handle_call is reserved).
    %% Phase 2: walks hierarchy to stdlib Supervisor/DynamicSupervisor methods.
    %% Phase 3: generated Module:'method'(Self) will be found first.
    case beamtalk_dispatch:lookup(Selector, Args, Self, #{}, ClassName) of
        {reply, Result, _} ->
            Result;
        {error, Error} ->
            beamtalk_exception_handler:reraise(Error)
    end;
send(Receiver, Selector, Args) ->
    case classify_receiver(Receiver) of
        primitive ->
            beamtalk_primitive:send(Receiver, Selector, Args);
        metaclass ->
            %% ADR 0036 (BT-802): Metaclass objects dispatch synchronously via
            %% the Metaclass → Class → Behaviour chain. They must NOT be treated
            %% as regular actor instances.
            beamtalk_primitive:send(Receiver, Selector, Args);
        {class, ClassPid} ->
            beamtalk_object_class:class_send(ClassPid, Selector, Args);
        {actor, Ref} ->
            %% BT-918 / ADR 0043: sync-by-default — use gen_server:call
            %% so the send returns the value directly, not a Future.
            beamtalk_actor:sync_send(Ref, Selector, Args);
        {dead, ClassName} ->
            reraise_actor_dead(ClassName, Selector)
    end.

-doc """
Send a message with explicit timeout (BT-1190).

Same as send/3 but passes Timeout to beamtalk_actor:sync_send/4.
For actor receivers, the timeout applies to gen_server:call. For value
types, metaclasses, and class objects, timeout is ignored and dispatch
falls through to the normal synchronous path.
""".
-spec send(term(), atom(), list(), timeout()) -> term().
send({beamtalk_future, _} = Future, Selector, Args, Timeout) ->
    %% BT-840 parity: auto-await futures before re-dispatching with timeout.
    Value = beamtalk_future:await(Future),
    send(Value, Selector, Args, Timeout);
send({beamtalk_supervisor, _, _, _} = Sup, Selector, Args, _Timeout) ->
    %% Supervisors dispatch via hierarchy walk (in-process, not gen_server:call),
    %% so timeout is irrelevant. Delegate to send/3.
    send(Sup, Selector, Args);
send(Receiver, Selector, Args, Timeout) ->
    case classify_receiver(Receiver) of
        primitive ->
            %% Value types have no timeout semantics — dispatch is synchronous in-process.
            beamtalk_primitive:send(Receiver, Selector, Args);
        metaclass ->
            beamtalk_primitive:send(Receiver, Selector, Args);
        {class, ClassPid} ->
            beamtalk_object_class:class_send(ClassPid, Selector, Args);
        {actor, Ref} ->
            beamtalk_actor:sync_send(Ref, Selector, Args, Timeout);
        {dead, ClassName} ->
            reraise_actor_dead(ClassName, Selector)
    end.

-doc """
Fire-and-forget cast to an actor receiver (BT-920).

For actors, extracts the PID and calls beamtalk_actor:cast_send/3.
Returns ok regardless of receiver type — non-actors are silently ignored
since cast has no meaningful semantics for primitives.
Auto-awaits futures before dispatching (BT-840 parity with send/3).
""".
-spec cast(term(), atom(), list()) -> ok.
cast({beamtalk_future, _} = Future, Selector, Args) ->
    Value = beamtalk_future:await(Future),
    cast(Value, Selector, Args);
cast(Receiver, Selector, Args) ->
    case classify_receiver(Receiver) of
        primitive ->
            %% Primitive receiver: cast has no effect
            ok;
        metaclass ->
            %% Metaclass objects cannot receive cast messages
            ok;
        {class, _ClassPid} ->
            %% Class objects cannot receive cast messages
            ok;
        {actor, Ref} ->
            beamtalk_actor:cast_send(Ref, Selector, Args);
        {dead, _ClassName} ->
            %% Dead actor: cast is fire-and-forget, silently ignore
            ok
    end.

-doc """
Send a reflected number-on-the-left coercion message, hinting the DNU if the
reflected method is genuinely missing (ADR 0116 § Dispatch mechanism).

Wraps send/3 for the `<verb>FromNumber:` call sites codegen emits for
`5 + aVector`-shaped expressions: `Right` is the non-numeric right operand,
`Selector` the synthesized reflected-method name (e.g. `'plusFromNumber:'`),
`Args` its argument list (the original left operand), and `OrigOp` the
original source operator symbol (e.g. `'+'`) used only for the hint text.

On success, returns send/3's result unchanged. On a `does_not_understand`
whose class and selector match `Right`'s actual class and this exact
`Selector` — i.e. the reflected method is genuinely absent from `Right`'s
class — re-raises the same error with a hint naming the original operator,
so `5 + aThing` fails with something closer to "`Thing` has no
`plusFromNumber:` — implement it to support `number + Thing` arithmetic"
than an unexplained DNU referencing a selector the caller never typed.

Any other exception propagates unchanged via erlang:raise/3: a DNU for a
*different* selector or class (e.g. a bug inside a *present* reflected
method's own body that itself DNUs on something else), or a non-DNU error
entirely. `kind` stays `does_not_understand` on the re-raised error — only
`hint` changes, so `on: RuntimeError do:`/`on: Error do:` catch it exactly
as before.

A DNU raised via `beamtalk_error:raise/1` is wrapped by
`beamtalk_exception_handler:wrap/1` into a `#{'$beamtalk_class' := _, error
:= #beamtalk_error{}}` tagged map *before* being raised (mirroring every
other DNU in the system, e.g. `raise_class_dnu` in
beamtalk_class_dispatch.erl) — the catch clause below matches that wrapped
shape, not the bare record, and the re-raise re-wraps the hinted error the
same way.
""".
-spec send_number_coercion(term(), atom(), list(), atom()) -> term().
send_number_coercion(Right, Selector, Args, OrigOp) ->
    RightClass = beamtalk_primitive:class_of(Right),
    try
        send(Right, Selector, Args)
    catch
        error:#{
            '$beamtalk_class' := _,
            error := #beamtalk_error{
                kind = does_not_understand,
                class = RightClass,
                selector = Selector
            } = Error
        }:Stack ->
            Hint = unicode:characters_to_binary(
                io_lib:format(
                    "~s has no '~s' — implement it to support 'number ~s ~s' arithmetic",
                    [RightClass, Selector, OrigOp, RightClass]
                )
            ),
            HintedError = beamtalk_error:with_hint(Error, Hint),
            erlang:raise(error, beamtalk_exception_handler:wrap(HintedError), Stack)
    end.

-doc """
Classify a receiver for dispatch, shared by send/3, send/4, cast/3 (BT-2787).
`{actor, Ref}` covers live actors (Ref: `pid()` or `{registered, Name}`,
ADR 0079). `{dead, ClassName}` covers an invalid PID slot (BT-886).
""".
-spec classify_receiver(term()) ->
    primitive | metaclass | {class, pid()} | {actor, term()} | {dead, atom()}.
classify_receiver(Receiver) ->
    case is_actor(Receiver) of
        false ->
            primitive;
        true ->
            case element(2, Receiver) of
                'Metaclass' ->
                    metaclass;
                _ ->
                    case beamtalk_class_registry:is_class_object(Receiver) of
                        true ->
                            {class, element(4, Receiver)};
                        false ->
                            Ref = element(4, Receiver),
                            case is_actor_ref(Ref) of
                                true ->
                                    {actor, Ref};
                                false ->
                                    {dead, element(2, Receiver)}
                            end
                    end
            end
    end.

-doc """
Raise the structured `actor_dead` error (BT-886), shared by send/3 and
send/4 so the error shape stays byte-identical.
""".
-spec reraise_actor_dead(atom(), atom()) -> no_return().
reraise_actor_dead(ClassName, Selector) ->
    Error = beamtalk_error:new(
        actor_dead,
        ClassName,
        Selector,
        <<"Actor process is not available; class may not be fully registered">>
    ),
    beamtalk_exception_handler:reraise(Error).

-doc """
Check if a value is a beamtalk actor (beamtalk_object record).

Uses safe short-circuit evaluation to avoid badarg on non-tuple values.
""".
-spec is_actor(term()) -> boolean().
is_actor(X) when is_tuple(X) ->
    tuple_size(X) =:= 4 andalso element(1, X) =:= beamtalk_object;
is_actor(_) ->
    false.

-doc """
Check whether a value is a valid actor identity slot — either a raw `pid()`
or a `{registered, Name}` proxy reference (ADR 0079 / BT-1990).
""".
-spec is_actor_ref(term()) -> boolean().
is_actor_ref(Ref) when is_pid(Ref) -> true;
is_actor_ref({registered, Name}) when is_atom(Name) -> true;
is_actor_ref(_) -> false.
