%% Copyright 2026 James Casey
%% SPDX-License-Identifier: Apache-2.0

-module(beamtalk_class_metadata).

%%% **DDD Context:** Object System Context

-moduledoc """
ETS table owner for the unified `beamtalk_class_metadata` table.

Holds the class-lifetime metadata that used to live in three separate
class-keyed ETS tables (`beamtalk_class_module`, `beamtalk_class_methods`,
`beamtalk_class_hierarchy`). They were consolidated (BT-2222) because they
shared a key (`ClassName`), a concurrency profile (`set` +
`{read_concurrency, true}`), a single writer (the class gen_server), and the
same three lifecycle points (`init`, `update_class`, `terminate`) — and the
`Module` field was duplicated across two of them.

## Row shape

Each row is a `#class_metadata{}` record keyed by `name`:

* `module`      — defining BEAM module, or `undefined` if unset
* `selectors`   — local class-method selectors, or `undefined` if unset
* `superclass`  — superclass atom, `none` for a root class, or `undefined` if unset
* `is_abstract` — whether the class is abstract, or `undefined` if unset (BT-3047 /
  ADR 0109 amendment)

`undefined` is the "field never written" sentinel and is distinct from `none`
(an explicitly root class). The typed lookups treat `undefined` as `not_found`,
so a row that carries only one field behaves exactly like the old per-table
absence of the others.

## Table properties

* Type: `set`, `{keypos, #class_metadata.name}` — one row per class name.
* Access: `public`, `named_table` — any process reads; written only by the
  class gen_server via `beamtalk_object_class`.
* `{read_concurrency, true}` — the hierarchy/module/methods reads are on hot
  dispatch and supervisor-init paths.
* Heir (BT-1888): created at app start by `beamtalk_runtime_app:start/2` (the
  long-lived app-master process owns it), then `start/2` re-runs `ensure_*` once
  the supervisor is alive so `beamtalk_runtime_sup` is set as `{heir, ...}`. The
  table therefore survives both a class-process crash and an app-master swap.

## Reverse subclass index (BT-3221)

`match_subclasses/1` is answered from a second table,
`beamtalk_class_subclass_index` — a `bag` of `{Superclass, ClassName}` edges,
keyed on `Superclass` — instead of an `ets:match/2` scan of every row in
`?TABLE`. A `bag` table (many rows per key) cannot share `?TABLE`'s `set`
semantics, so this is a genuine second table rather than a field on the
existing row; the "second table" it replaces is only the mental model of a
"seventh, independently-lifecycled table" that BT-2222 weighed against — this
one has no owner module, public API, or lifecycle of its own. It is created
and destroyed by this module's own `new/0`, and every write that can change a
row's `superclass` (`insert/5`, `merge_identity/5`, `delete/1`) maintains it
as an internal side effect via `sync_subclass_index/3`, keyed off the row's
*previous* superclass value (read via `field/2` before the write lands) so a
re-register that changes superclass removes the stale edge from the old
parent rather than leaving it to accumulate. Storing the edge independently of
the superclass's own row (rather than as a `subclasses` list field on it)
means a class's children stay discoverable even if the parent's own row is
gone (e.g. a crash mid-teardown) — matching the exact-scan semantics this
replaces, which never depended on the queried class having a row at all.

## Concurrency

`new/0` uses try/catch around `ets:new/2` for the TOCTOU race between
`ets:info/1` and `ets:new/2`. All read/write ops guard against `badarg` from
a table deleted between an existence check and the op (teardown/shutdown).
""".

-include("beamtalk.hrl").
%% BT-3085: generated by `beamtalk build-stdlib` (see build_stdlib.rs's
%% `generate_erlang_builtins_hrl`) — the Erlang-side twin of
%% generated_builtins.rs's `is_generated_builtin_class`. Defines
%% `?BEAMTALK_GENERATED_BUILTIN_CLASSES`, consumed by `all_builtins/0` below.
-include("beamtalk_generated_builtins.hrl").

-export([
    new/0,
    insert/5,
    merge_identity/5,
    delete/1,
    lookup_module/1,
    lookup_methods/1,
    lookup_superclass/1,
    lookup_is_abstract/1,
    match_subclasses/1,
    foldl/2,
    foldl_modules/2,
    all_builtins/0,
    %% BT-2266 / ADR 0084: runtime class-method fun retrieval store + gate flag.
    put_class_method_fun/3,
    lookup_class_method_fun/2,
    delete_class_method_funs/1,
    has_runtime_class_methods/1,
    set_runtime_class_methods/2,
    reset_runtime_class_methods/1
]).

-define(TABLE, beamtalk_class_metadata).
%% BT-2266 / ADR 0084: sibling table holding runtime-installed class-method funs,
%% keyed by {DefiningClass, Selector}. The metadata row's
%% `has_runtime_class_methods` flag gates reads on this table so compile-time-only
%% classes pay nothing on the dispatch hot path (BT-2008).
-define(FUN_TABLE, beamtalk_class_method_funs).
%% BT-3221: reverse-edge index for match_subclasses/1 — a `bag` of
%% {Superclass, ClassName} rows, keyed on Superclass. See moduledoc "Reverse
%% subclass index".
-define(SUBCLASS_INDEX, beamtalk_class_subclass_index).

-type class_name() :: atom().
-type superclass() :: class_name() | none.
-type selector() :: atom().
-type class_method_fun_info() :: #{block := fun(), arity := non_neg_integer()}.

-record(class_metadata, {
    name :: class_name(),
    module :: module() | undefined,
    selectors :: [selector()] | undefined,
    superclass :: superclass() | undefined,
    %% BT-2266 / ADR 0084: true once a runtime/builder class-method fun has been
    %% installed for this class. The dispatch-time gate: false means the funs
    %% table is never read for this class.
    has_runtime_class_methods = false :: boolean(),
    %% BT-3047 / ADR 0109 amendment: whether the class is abstract, read by the
    %% instantiation intrinsics (`self spawn`/`self spawnWith:`/etc.) instead of
    %% the `beamtalk_class_is_abstract` process-dictionary flag, which resolves
    %% against the wrong class when read from inside a block executing in a
    %% foreign class's process. `undefined` (the "field never written" sentinel,
    %% not a boolean default — see `lookup_is_abstract/1`) rather than `false`,
    %% because a class-existence guard must not silently default toward
    %% *permitting* instantiation on a lookup miss.
    is_abstract :: boolean() | undefined
}).

%%====================================================================
%% Table lifecycle
%%====================================================================

-doc """
Ensure the unified class metadata ETS table exists (idempotent).

Creates the table on first call; subsequent calls retroactively set the heir
once the supervisor is alive (BT-1888). Safe to call concurrently — a try/catch
handles the race between `ets:info/1` and `ets:new/2`.
""".
-spec new() -> ok.
new() ->
    ensure_table(?TABLE, [
        set,
        public,
        named_table,
        {keypos, #class_metadata.name},
        {read_concurrency, true}
    ]),
    %% BT-2266: the funs table is a plain {Key, Value} set (default keypos 1),
    %% Key = {DefiningClass, Selector}, Value = #{block, arity}.
    ensure_table(?FUN_TABLE, [
        set,
        public,
        named_table,
        {read_concurrency, true}
    ]),
    %% BT-3221: reverse-edge index, {Superclass, ClassName} rows, default
    %% keypos 1 (Superclass). `bag` because a superclass has many subclasses.
    ensure_table(?SUBCLASS_INDEX, [
        bag,
        public,
        named_table,
        {read_concurrency, true}
    ]),
    ok.

-spec ensure_table(atom(), [term()]) -> ok.
ensure_table(Table, Opts) ->
    case ets:info(Table) of
        undefined ->
            try
                ets:new(Table, Opts ++ beamtalk_class_registry:heir_option()),
                ok
            catch
                error:badarg -> ok
            end;
        _ ->
            beamtalk_class_registry:maybe_set_heir(Table),
            ok
    end.

%%====================================================================
%% Writes
%%====================================================================

-doc """
Insert or overwrite the **entire** metadata row for a class — row *creation*.

This is a full-row write, not a per-field merge: every call replaces all of
`module`, `selectors`, `superclass`, `is_abstract`, **and resets
`has_runtime_class_methods` to `false`**. The class gen_server calls this only
from `init/1`, where the row is genuinely new (or being recreated after
teardown), so resetting the gate is correct — a brand-new row has no runtime
funs installed yet. Pass `undefined` only to leave a field genuinely unset
(used by tests that exercise one field in isolation, and by callers that don't
know `is_abstract` — BT-3047 / ADR 0109 amendment).

BT-3107: do NOT call this to update an **existing** row — besides wiping any
field you don't pass explicitly, it silently drops
`has_runtime_class_methods`, discarding every runtime class method unless the
caller remembers a follow-up `seed_runtime_class_methods/2` (the documented
footgun this issue closed). Use `merge_identity/5` for updating an existing
row instead; it never touches the gate.
""".
-spec insert(
    class_name(),
    module() | undefined,
    [selector()] | undefined,
    superclass() | undefined,
    boolean() | undefined
) ->
    ok.
insert(Name, Module, Selectors, Superclass, IsAbstract) ->
    Row = #class_metadata{
        name = Name,
        module = Module,
        selectors = Selectors,
        superclass = Superclass,
        is_abstract = IsAbstract
    },
    new(),
    %% BT-3221: read the row's previous superclass (undefined if there was no
    %% row yet) before overwriting it, so the subclass index can drop the
    %% stale edge from the old superclass if this call changes it.
    OldSuperclass = field(Name, #class_metadata.superclass),
    try
        ets:insert(?TABLE, Row),
        sync_subclass_index(Name, OldSuperclass, Superclass),
        ok
    catch
        error:badarg ->
            %% Table vanished between new/0 and ets:insert/2 — recreate and retry once.
            new(),
            ets:insert(?TABLE, Row),
            sync_subclass_index(Name, OldSuperclass, Superclass),
            ok
    end.

-doc """
Merge identity fields into an **existing** metadata row — row *update*.

BT-3107: per-field update of `module`, `selectors`, `superclass`, and
`is_abstract` via `ets:update_element/3`; unlike `insert/5` it never touches
`has_runtime_class_methods`, so a caller that reloads a class's identity
cannot accidentally wipe its runtime class methods by forgetting a follow-up
`seed_runtime_class_methods/2` call. A caller that genuinely needs to drop the
gate (e.g. because it just purged the funs table via
`delete_class_method_funs/1`) must say so explicitly via
`reset_runtime_class_methods/1` — the two are never an implicit side effect of
each other.

Falls back to a full `insert/5` (gate defaults to `false`) if no row exists
yet for `Name` — the reload path this backs (`beamtalk_object_class:
apply_class_info/2`) always has a row already (the class went through
`init/1`), but this keeps the function correct standalone and in tests.
""".
-spec merge_identity(
    class_name(),
    module() | undefined,
    [selector()] | undefined,
    superclass() | undefined,
    boolean() | undefined
) ->
    ok.
merge_identity(Name, Module, Selectors, Superclass, IsAbstract) ->
    new(),
    %% BT-3221: read the previous superclass before the update lands, so a
    %% re-register that changes superclass can drop the stale reverse edge
    %% from the old parent (see sync_subclass_index/3).
    OldSuperclass = field(Name, #class_metadata.superclass),
    %% ets:update_element/3 does NOT raise on a missing key — it returns
    %% `false` (only a missing/unwritable *table* raises badarg) — so the
    %% fallback to row creation must branch on the boolean return, not on a
    %% caught exception.
    try
        ets:update_element(?TABLE, Name, [
            {#class_metadata.module, Module},
            {#class_metadata.selectors, Selectors},
            {#class_metadata.superclass, Superclass},
            {#class_metadata.is_abstract, IsAbstract}
        ])
    of
        true ->
            sync_subclass_index(Name, OldSuperclass, Superclass),
            ok;
        false ->
            %% No existing row — fall back to row creation. A brand-new row
            %% has no funs to preserve, so insert/5's gate reset is correct.
            %% insert/5 re-reads the (still-absent) old superclass itself, so
            %% this never double-applies the index update.
            insert(Name, Module, Selectors, Superclass, IsAbstract)
    catch
        error:badarg ->
            %% Table vanished between new/0 and the update — recreate via insert/5.
            insert(Name, Module, Selectors, Superclass, IsAbstract)
    end.

-doc """
Remove a class's metadata row.

Called from the class gen_server `terminate/2`. Safe if the row — or the table —
does not exist.
""".
-spec delete(class_name()) -> ok.
delete(Name) ->
    %% BT-2266: drop any runtime class-method funs alongside the metadata row so
    %% a class that is removed (or whose process terminates) leaves no stale
    %% dispatch entries behind.
    delete_class_method_funs(Name),
    %% BT-3221: read the superclass before the row disappears, so the reverse
    %% edge {Superclass, Name} can be dropped from the subclass index too —
    %% otherwise Name would linger forever as a phantom subclass of its old
    %% superclass. This does NOT touch edges keyed on Name itself (i.e. rows
    %% for Name's own children) — those stay valid; a class's children remain
    %% discoverable even if its own row is gone (see moduledoc).
    OldSuperclass = field(Name, #class_metadata.superclass),
    try
        ets:delete(?TABLE, Name),
        sync_subclass_index(Name, OldSuperclass, undefined),
        ok
    catch
        error:badarg -> ok
    end.

%%====================================================================
%% Reads
%%====================================================================

-doc "Look up a class's module name. `undefined`/missing yields `not_found`.".
-spec lookup_module(class_name()) -> {ok, module()} | not_found.
lookup_module(Name) ->
    case field(Name, #class_metadata.module) of
        undefined -> not_found;
        Module -> {ok, Module}
    end.

-doc """
Look up a class's module and local class-method selectors.

Returns `{ok, Module, Selectors}` only when both fields have been written (an
empty selector list is valid); otherwise `not_found`. The two are always written
together (`insert/4`), so requiring a non-`undefined` module keeps the return
honest with the `module()` spec even if a row carries only one of them.
""".
-spec lookup_methods(class_name()) -> {ok, module(), [selector()]} | not_found.
lookup_methods(Name) ->
    case row(Name) of
        {ok, #class_metadata{module = undefined}} -> not_found;
        {ok, #class_metadata{selectors = undefined}} -> not_found;
        {ok, #class_metadata{module = Module, selectors = Selectors}} -> {ok, Module, Selectors};
        not_found -> not_found
    end.

-doc """
Look up a class's superclass.

Returns `{ok, none}` for a root class and `{ok, Super}` otherwise; `not_found`
when the superclass field has not been written.
""".
-spec lookup_superclass(class_name()) -> {ok, superclass()} | not_found.
lookup_superclass(Name) ->
    case field(Name, #class_metadata.superclass) of
        undefined -> not_found;
        Super -> {ok, Super}
    end.

-doc """
Look up whether a class is abstract (BT-3047 / ADR 0109 amendment).

Returns `not_found` — never a defaulted boolean — when the row or field is
unset. Callers that use this to gate instantiation (e.g.
`beamtalk_class_instantiation:resolve_is_abstract_or_raise/2`) must not
silently pick either boolean on a miss: `false` would let a genuinely abstract
class be constructed if the row hasn't been written yet, and `true` would
wrongly refuse a genuinely concrete one. A miss should never happen for a live,
already-dispatching class (the row is written unconditionally at the same
`init`/reload point that establishes the class's other identity), so `not_found`
here indicates a bug worth surfacing loudly rather than a normal case to paper
over with a default.
""".
-spec lookup_is_abstract(class_name()) -> {ok, boolean()} | not_found.
lookup_is_abstract(Name) ->
    case field(Name, #class_metadata.is_abstract) of
        undefined -> not_found;
        IsAbstract -> {ok, IsAbstract}
    end.

-doc """
Return all class names whose direct superclass is `Name`.

BT-3221: an indexed `ets:lookup/2` on the `beamtalk_class_subclass_index`
reverse-edge table, not a full-table scan of `?TABLE` — O(subclass count)
instead of O(loaded-class count). Returns `[]` if the index table does not
exist (mirrors the old table-absent contract, now against the table this
function actually reads).
""".
-spec match_subclasses(class_name()) -> [class_name()].
match_subclasses(Name) ->
    case ets:info(?SUBCLASS_INDEX) of
        undefined ->
            [];
        _ ->
            try
                [ClassName || {_Superclass, ClassName} <- ets:lookup(?SUBCLASS_INDEX, Name)]
            catch
                error:badarg -> []
            end
    end.

-doc """
Fold over `{ClassName, Superclass}` pairs for every row with a known superclass.

Rows whose superclass field is unset (`undefined`) are skipped, preserving the
behaviour of the former hierarchy table, which only contained rows that had a
superclass written. Returns `Acc0` if the table does not exist.
""".
-spec foldl(fun(({class_name(), superclass()}, Acc) -> Acc), Acc) -> Acc.
foldl(Fun, Acc0) ->
    case ets:info(?TABLE) of
        undefined ->
            Acc0;
        _ ->
            try
                ets:foldl(
                    fun
                        (#class_metadata{superclass = undefined}, Acc) -> Acc;
                        (#class_metadata{name = N, superclass = S}, Acc) -> Fun({N, S}, Acc)
                    end,
                    Acc0,
                    ?TABLE
                )
            catch
                error:badarg -> Acc0
            end
    end.

-doc """
Fold over `{ClassName, Module}` pairs for every row with a known module.

BT-3081: gives `beamtalk_class_registry:module_to_class_map/0` an ETS-only
(no gen_server calls) way to build the module→class map, instead of scanning
every live class process via `live_class_entries/0`. Rows whose module field
is unset (`undefined`) are skipped. Returns `Acc0` if the table does not exist.
""".
-spec foldl_modules(fun(({class_name(), module()}, Acc) -> Acc), Acc) -> Acc.
foldl_modules(Fun, Acc0) ->
    case ets:info(?TABLE) of
        undefined ->
            Acc0;
        _ ->
            try
                ets:foldl(
                    fun
                        (#class_metadata{module = undefined}, Acc) -> Acc;
                        (#class_metadata{name = N, module = M}, Acc) -> Fun({N, M}, Acc)
                    end,
                    Acc0,
                    ?TABLE
                )
            catch
                error:badarg -> Acc0
            end
    end.

-doc """
Return all stdlib builtin class names known to the Rust compiler.

These classes are already in `ClassHierarchy::with_builtins()` on the Rust side
with richer data than `__beamtalk_meta/0` provides. Crash recovery skips them so
the Rust compiler's richer definitions take precedence.

BT-3085: `?BEAMTALK_GENERATED_BUILTIN_CLASSES` (from the generated
`beamtalk_generated_builtins.hrl`, regenerated by `beamtalk build-stdlib`
alongside `generated_builtins.rs::is_generated_builtin_class` from the same
stdlib class-metadata pass) plus `'Future'`, the one runtime-only class with
no `stdlib/src/Future.bt` source — mirroring `builtins.rs::is_builtin_class`
on the Rust side. Do not hand-edit the class list; regenerate via `just build`
/ `beamtalk build-stdlib` instead.
""".
-spec all_builtins() -> [atom()].
all_builtins() ->
    ['Future' | ?BEAMTALK_GENERATED_BUILTIN_CLASSES].

%%====================================================================
%% Runtime class-method funs (BT-2266 / ADR 0084)
%%====================================================================

-doc """
Write a runtime/builder-installed class-method fun into the retrieval store.

Keyed by `{DefiningClass, Selector}` so inherited dispatch can fetch the fun
after the chain walk resolves the defining class — without a `gen_server` hop
(BT-2008). Callers must also flip the gate flag via `set_runtime_class_methods/2`
(write the fun first, publish the flag second) so a reader never sees an enabled
gate without the fun present.
""".
-spec put_class_method_fun(class_name(), selector(), class_method_fun_info()) -> ok.
put_class_method_fun(Name, Selector, Info) ->
    new(),
    Key = {Name, Selector},
    try
        ets:insert(?FUN_TABLE, {Key, Info}),
        ok
    catch
        error:badarg ->
            new(),
            ets:insert(?FUN_TABLE, {Key, Info}),
            ok
    end.

-doc """
Fetch a runtime class-method fun for `{DefiningClass, Selector}`.

Gated on the per-class `has_runtime_class_methods` flag: a compile-time-only
class returns `error` without ever reading the funs table (the BT-2008 hot-path
guarantee). Returns `{ok, #{block, arity}}` when a runtime fun is installed.
""".
-spec lookup_class_method_fun(class_name(), selector()) ->
    {ok, class_method_fun_info()} | error.
lookup_class_method_fun(Name, Selector) ->
    case has_runtime_class_methods(Name) of
        false ->
            error;
        true ->
            case ets:info(?FUN_TABLE) of
                undefined ->
                    error;
                _ ->
                    try ets:lookup(?FUN_TABLE, {Name, Selector}) of
                        [{_, Info}] -> {ok, Info};
                        [] -> error
                    catch
                        error:badarg -> error
                    end
            end
    end.

-doc """
Remove every runtime class-method fun installed for `Name`.

Called on class teardown (`delete/1`) and before re-seeding on `update_class`
reload, so memory-only runtime methods do not survive a recompile (ADR 0082).
""".
-spec delete_class_method_funs(class_name()) -> ok.
delete_class_method_funs(Name) ->
    case ets:info(?FUN_TABLE) of
        undefined ->
            ok;
        _ ->
            try
                ets:match_delete(?FUN_TABLE, {{Name, '_'}, '_'}),
                ok
            catch
                error:badarg -> ok
            end
    end.

-doc """
Read the per-class "has runtime class methods" gate flag.

`false` (the default for compile-time-only classes) means dispatch skips the
funs-table read entirely. Exposed for dispatch gating and tests.
""".
-spec has_runtime_class_methods(class_name()) -> boolean().
has_runtime_class_methods(Name) ->
    case field(Name, #class_metadata.has_runtime_class_methods) of
        true -> true;
        _ -> false
    end.

-doc """
Atomically publish the class's local selectors and set the gate flag.

Used by `init`/`update_class` seeding and live `put_class_method`: the funs are
written first (`put_class_method_fun/3`), then this single `update_element`
publishes the new selector set together with the gate flag, so a concurrent
reader never observes a discoverable selector whose gate is still closed.
Leaves `module` and `superclass` untouched. A no-op if the row is absent.
""".
-spec set_runtime_class_methods(class_name(), [selector()]) -> ok.
set_runtime_class_methods(Name, Selectors) ->
    new(),
    try
        ets:update_element(?TABLE, Name, [
            {#class_metadata.selectors, Selectors},
            {#class_metadata.has_runtime_class_methods, true}
        ]),
        ok
    catch
        error:badarg -> ok
    end.

-doc """
Explicitly clear the "has runtime class methods" gate, independent of any
other field.

BT-3107: pairs with `delete_class_method_funs/1` when purging a class's funs
table ahead of a reload — together they are the reload path's explicit,
self-documenting substitute for `insert/5`'s old implicit reset via full-row
overwrite (see `merge_identity/5`, which deliberately leaves the gate alone).
A no-op if the row is absent.
""".
-spec reset_runtime_class_methods(class_name()) -> ok.
reset_runtime_class_methods(Name) ->
    new(),
    try
        ets:update_element(?TABLE, Name, [
            {#class_metadata.has_runtime_class_methods, false}
        ]),
        ok
    catch
        error:badarg -> ok
    end.

%%====================================================================
%% Internal
%%====================================================================

%% BT-3221: reconcile the {Superclass, ClassName} reverse-edge index with a
%% row write that set Name's superclass to NewSuperclass, given the value it
%% held immediately before (OldSuperclass, `undefined` if there was no prior
%% row or the field was never written). A no-op when the value didn't change
%% (covers the common re-register-with-same-superclass case, and repeated
%% `undefined` writes). `undefined` never has a corresponding index row —
%% only actually-written superclass values (including the literal atom
%% `none` for a root class) do — so it is never inserted or deleted as an
%% edge target. Best-effort: a table-absent race (only possible mid-teardown,
%% since new/0 always runs first in every caller) degrades to leaving the
%% index momentarily stale rather than crashing the write it is attached to.
-spec sync_subclass_index(class_name(), superclass() | undefined, superclass() | undefined) -> ok.
sync_subclass_index(_Name, Same, Same) ->
    ok;
sync_subclass_index(Name, OldSuperclass, NewSuperclass) ->
    case OldSuperclass of
        undefined -> ok;
        _ -> delete_subclass_edge(OldSuperclass, Name)
    end,
    case NewSuperclass of
        undefined -> ok;
        _ -> insert_subclass_edge(NewSuperclass, Name)
    end,
    ok.

-spec insert_subclass_edge(superclass(), class_name()) -> ok.
insert_subclass_edge(Superclass, Name) ->
    try
        ets:insert(?SUBCLASS_INDEX, {Superclass, Name}),
        ok
    catch
        error:badarg -> ok
    end.

-spec delete_subclass_edge(superclass(), class_name()) -> ok.
delete_subclass_edge(Superclass, Name) ->
    try
        ets:delete_object(?SUBCLASS_INDEX, {Superclass, Name}),
        ok
    catch
        error:badarg -> ok
    end.

%% Fetch a single field via ets:lookup_element/4 (OTP 26+), which copies only
%% that element instead of the whole row — measurably faster than ets:lookup/2
%% on the hierarchy-walk hot path (inherits_from/2). The `undefined` default
%% collapses the three not_found cases (table absent, key absent, field unset)
%% into one return value, since none of them is a valid written field value.
-spec field(class_name(), pos_integer()) -> term().
field(Name, Pos) ->
    case ets:info(?TABLE) of
        undefined ->
            undefined;
        _ ->
            try
                ets:lookup_element(?TABLE, Name, Pos, undefined)
            catch
                error:badarg -> undefined
            end
    end.

-spec row(class_name()) -> {ok, #class_metadata{}} | not_found.
row(Name) ->
    case ets:info(?TABLE) of
        undefined ->
            not_found;
        _ ->
            try ets:lookup(?TABLE, Name) of
                [Row] -> {ok, Row};
                [] -> not_found
            catch
                error:badarg -> not_found
            end
    end.
