// Copyright 2026 James Casey
// SPDX-License-Identifier: Apache-2.0

//! Build script to auto-generate test functions from test case directories.
//!
//! This script scans the `cases/` directory and generates a test function
//! for each subdirectory containing a `main.bt` file.

use std::env;
use std::fs;
use std::io::Write;
use std::path::Path;

fn main() {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let cases_dir = Path::new(&manifest_dir).join("cases");

    // Watch the cases directory for changes
    println!("cargo:rerun-if-changed={}", cases_dir.display());

    // Find all test cases
    let mut test_cases = Vec::new();
    if cases_dir.exists() {
        for entry in fs::read_dir(&cases_dir).unwrap() {
            let entry = entry.unwrap();
            let path = entry.path();

            if path.is_dir() {
                let main_bt = path.join("main.bt");
                if main_bt.exists() {
                    let case_name = path.file_name().unwrap().to_str().unwrap().to_string();
                    test_cases.push(case_name);
                }
            }
        }
    }

    // Sort test cases for consistent ordering
    test_cases.sort();

    // Generate test functions
    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated_tests.rs");
    let mut f = fs::File::create(&dest_path).unwrap();

    writeln!(f, "// Auto-generated test functions").unwrap();
    writeln!(f, "// Do not edit this file manually\n").unwrap();

    for case_name in &test_cases {
        // Generate lexer test
        writeln!(f, "#[test]").unwrap();
        writeln!(f, "fn test_{}_lexer() {{", case_name).unwrap();
        writeln!(f, "    test_lexer_snapshot(\"{}\");", case_name).unwrap();
        writeln!(f, "}}\n").unwrap();

        // Generate parser test
        writeln!(f, "#[test]").unwrap();
        writeln!(f, "fn test_{}_parser() {{", case_name).unwrap();
        writeln!(f, "    test_parser_snapshot(\"{}\");", case_name).unwrap();
        writeln!(f, "}}\n").unwrap();
    }

    println!("Generated {} test cases", test_cases.len());
}
