%% Copyright 2026 James Casey
%% SPDX-License-Identifier: Apache-2.0

-module(beamtalk_cerl_wire_tests).

-moduledoc """
ADR 0088 Phase 0b napkin smoke tests (BT-2315).

Drives the new `{cerl, Etf}' Port message variant end-to-end on both
compile paths:

  * `beamtalk_compiler_server:compile_core_erlang/1' (no `debug_info').
  * `beamtalk_build_worker:compile_core_erlang/1'   (with `debug_info').

The acceptance criteria explicitly require both paths because the
`compile:forms/2' options differ — annotation chunks land in `debug_info'
on the build path, and the napkin must verify nothing surprises us there
when Phase 1 lands.

The test also doubles as the **byte-equivalence fixture** for the Rust
side: the canonical ETF bytes produced by `term_to_binary/1' applied to
the same cerl terms here are also hard-coded in
`crates/beamtalk-core/src/codegen/core_erlang/cerl.rs' so the Rust
encoder's output can be diff'd against this reference without a runtime
dependency between the two test suites. `scripts/cerl-napkin-dump.escript'
regenerates both byte sets.
""".

-include_lib("eunit/include/eunit.hrl").

%%% ----------------------------------------------------------------
%%% Helpers
%%% ----------------------------------------------------------------

%% The truly-empty module shape — no defs, no exports. The byte-equivalence
%% test below pins its layout. This shape is *not* loadable as a useful
%% module (no `module_info/0,1' is auto-generated by `from_core'), so the
%% end-to-end load tests use `minimum_module_term/1' instead.
empty_module_term() ->
    cerl:c_module(cerl:c_atom(bt_napkin), [], [], []).

%% The minimum module shape: a self-identifying module exporting
%% `module_info/0' + `module_info/1', both delegating to the corresponding
%% `erlang:get_module_info' BIF. This is the smallest cerl tree that
%% satisfies the AC's `module_info(module) =:= bt_napkin' check.
minimum_module_term(ModName) ->
    Mi0Var = cerl:c_var({module_info, 0}),
    Mi1Var = cerl:c_var({module_info, 1}),
    Mi0Fun = cerl:c_fun(
        [],
        cerl:c_call(
            cerl:c_atom(erlang),
            cerl:c_atom(get_module_info),
            [cerl:c_atom(ModName)]
        )
    ),
    X = cerl:c_var('X'),
    Mi1Fun = cerl:c_fun(
        [X],
        cerl:c_call(
            cerl:c_atom(erlang),
            cerl:c_atom(get_module_info),
            [cerl:c_atom(ModName), X]
        )
    ),
    Defs = [{Mi0Var, Mi0Fun}, {Mi1Var, Mi1Fun}],
    cerl:c_module(cerl:c_atom(ModName), [Mi0Var, Mi1Var], [], Defs).

%% Wrap a cerl module in the `{cerl, Etf}' Port message variant.
cerl_msg(Mod) ->
    {cerl, term_to_binary(Mod)}.

%% Module-name suffixes so server/build_worker tests use distinct names —
%% loading the same module twice would clash on `code:purge'.
unique_module_name(Suffix) ->
    Bin = atom_to_binary(Suffix, utf8),
    binary_to_atom(<<"bt_napkin_", Bin/binary>>, utf8).

%%% ----------------------------------------------------------------
%%% Byte-equivalence fixture (Erlang side)
%%% ----------------------------------------------------------------
%%
%% These constants are the canonical Phase 0b reference bytes. The Rust
%% encoder must produce the same byte sequences — see
%% `EMPTY_BT_NAPKIN_ETF` and `MINIMUM_BT_NAPKIN_ETF` in
%% `crates/beamtalk-core/src/codegen/core_erlang/cerl.rs`.
%%
%% If they ever change (extremely unlikely — cerl record shape has been
%% stable since OTP 18), regenerate via
%% `scripts/cerl-napkin-dump.escript' and update both sides in lockstep.

empty_module_etf_layout_test() ->
    Reference = <<
        131,
        104,
        6,
        119,
        8,
        "c_module",
        106,
        104,
        3,
        119,
        9,
        "c_literal",
        106,
        119,
        9,
        "bt_napkin",
        106,
        106,
        106
    >>,
    ?assertEqual(Reference, term_to_binary(empty_module_term())).

minimum_module_etf_size_test() ->
    %% The minimum module's exact byte sequence is large (407 bytes); we
    %% pin the size here and rely on the Rust-side byte-equivalence assertion
    %% to verify the full layout. Both ends regenerate from the same
    %% escript so drift surfaces immediately.
    Bytes = term_to_binary(minimum_module_term(bt_napkin)),
    ?assertEqual(407, byte_size(Bytes)).

%%% ----------------------------------------------------------------
%%% compile_core_erlang/1 — `{cerl, Etf}` variant on the server path
%%% (no `debug_info`)
%%% ----------------------------------------------------------------

cerl_variant_compiles_empty_module_test() ->
    %% A literally-empty cerl module (no defs/exports) still compiles
    %% successfully — it just isn't loadable as a useful module. This test
    %% pins that the wire arm accepts the smallest possible payload.
    Result = beamtalk_compiler_server:compile_core_erlang(cerl_msg(empty_module_term())),
    ?assertMatch({ok, bt_napkin, _}, Result).

cerl_variant_compiles_minimum_module_test() ->
    Name = unique_module_name(server),
    Result = beamtalk_compiler_server:compile_core_erlang(
        cerl_msg(minimum_module_term(Name))
    ),
    ?assertMatch({ok, _, _}, Result),
    {ok, ModuleName, Binary} = Result,
    ?assertEqual(Name, ModuleName),
    ?assert(is_binary(Binary)),
    ?assert(byte_size(Binary) > 0).

cerl_variant_module_loads_and_reports_name_test() ->
    %% End-to-end smoke: Rust would construct the cerl term and ship ETF
    %% across the Port; here we do it locally with `term_to_binary' to
    %% exercise only the Erlang half of the wire contract (the byte-equiv
    %% test above proves the Rust half produces the same bytes).
    Name = unique_module_name(load_server),
    {ok, Name, Binary} = beamtalk_compiler_server:compile_core_erlang(
        cerl_msg(minimum_module_term(Name))
    ),
    {module, Name} = code:load_binary(Name, atom_to_list(Name) ++ ".beam", Binary),
    try
        ?assertEqual(Name, Name:module_info(module))
    after
        code:purge(Name),
        code:delete(Name)
    end.

cerl_variant_rejects_malformed_etf_test() ->
    Result = beamtalk_compiler_server:compile_core_erlang(
        {cerl, <<"not etf at all">>}
    ),
    ?assertMatch({error, {cerl_decode_error, _}}, Result).

cerl_variant_text_path_still_works_test() ->
    %% Sanity: adding the `{cerl, Etf}' clause must not break the existing
    %% binary text wire.
    Text = <<
        "module 'cerl_napkin_text_check' ['hello'/0]\n"
        "  attributes []\n"
        "  'hello'/0 = fun () -> 'world'\n"
        "end\n"
    >>,
    ?assertMatch(
        {ok, cerl_napkin_text_check, _},
        beamtalk_compiler_server:compile_core_erlang(Text)
    ).

%%% ----------------------------------------------------------------
%%% compile_core_erlang/1 — `{cerl, Etf}` variant on the build_worker
%%% path (with `debug_info`)
%%% ----------------------------------------------------------------

build_worker_cerl_variant_compiles_minimum_module_test() ->
    Name = unique_module_name(build_worker),
    Result = beamtalk_build_worker:compile_core_erlang(
        cerl_msg(minimum_module_term(Name))
    ),
    ?assertMatch({ok, _, _}, Result),
    {ok, ModuleName, Binary} = Result,
    ?assertEqual(Name, ModuleName),
    ?assert(is_binary(Binary)),
    ?assert(byte_size(Binary) > 0).

build_worker_cerl_emits_debug_info_test() ->
    %% The build_worker path adds `debug_info' to `compile:forms/2'.
    %% Confirm the chunk is present — ADR 0088 explicitly calls out that
    %% the napkin must exercise both with-and-without-`debug_info' options
    %% so Phase 1 doesn't hit an annotation-chunk surprise on the build
    %% path.
    Name = unique_module_name(debug_info),
    {ok, Name, Binary} = beamtalk_build_worker:compile_core_erlang(
        cerl_msg(minimum_module_term(Name))
    ),
    {ok, {Name, Chunks}} = beam_lib:chunks(Binary, ["Dbgi"]),
    ?assertMatch([{"Dbgi", _}], Chunks).

build_worker_cerl_loadable_test() ->
    Name = unique_module_name(load_worker),
    {ok, Name, Binary} = beamtalk_build_worker:compile_core_erlang(
        cerl_msg(minimum_module_term(Name))
    ),
    {module, Name} = code:load_binary(Name, atom_to_list(Name) ++ ".beam", Binary),
    try
        ?assertEqual(Name, Name:module_info(module))
    after
        code:purge(Name),
        code:delete(Name)
    end.

build_worker_cerl_variant_rejects_malformed_etf_test() ->
    Result = beamtalk_build_worker:compile_core_erlang(
        {cerl, <<0, 1, 2, 3>>}
    ),
    ?assertMatch({error, {cerl_decode_error, _}}, Result).
